// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as KardApi from "../../../../../index.js";

export declare namespace ContentStrategiesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ContentStrategiesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ContentStrategiesClient.Options>;

    constructor(options: ContentStrategiesClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Create a content strategy for the organization. The strategy name must be unique within the organization.
     *
     * @param {string} organizationId - Unique identifier of the organization
     * @param {KardApi.organizations.CreateContentStrategyRequestBody} request
     * @param {ContentStrategiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link KardApi.UnauthorizedError}
     * @throws {@link KardApi.ForbiddenError}
     * @throws {@link KardApi.InvalidRequest}
     * @throws {@link KardApi.ConflictError}
     * @throws {@link KardApi.DoesNotExistError}
     * @throws {@link KardApi.InternalServerError}
     *
     * @example
     *     await client.organizations.contentStrategies.create("org-123", {
     *         data: {
     *             type: "contentStrategy",
     *             attributes: {
     *                 name: "Featured Travel",
     *                 filter: "HIGHEST_CASHBACK",
     *                 categories: ["Travel"],
     *                 categoryExclusions: ["Gas"],
     *                 merchantExclusions: ["merchant-abc"]
     *             }
     *         }
     *     })
     */
    public create(
        organizationId: string,
        request: KardApi.organizations.CreateContentStrategyRequestBody,
        requestOptions?: ContentStrategiesClient.RequestOptions,
    ): core.HttpResponsePromise<KardApi.organizations.ContentStrategyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(organizationId, request, requestOptions));
    }

    private async __create(
        organizationId: string,
        request: KardApi.organizations.CreateContentStrategyRequestBody,
        requestOptions?: ContentStrategiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<KardApi.organizations.ContentStrategyResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KardApiEnvironment.Production,
                `v2/issuers/${core.url.encodePathParam(organizationId)}/contentStrategies`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as KardApi.organizations.ContentStrategyResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new KardApi.UnauthorizedError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new KardApi.ForbiddenError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 400:
                    throw new KardApi.InvalidRequest(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new KardApi.ConflictError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new KardApi.DoesNotExistError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new KardApi.InternalServerError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KardApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v2/issuers/{organizationId}/contentStrategies",
        );
    }

    /**
     * List content strategies belonging to the authenticated organization
     *
     * @param {string} organizationId - Unique identifier of the organization
     * @param {KardApi.organizations.ListContentStrategiesRequest} request
     * @param {ContentStrategiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link KardApi.UnauthorizedError}
     * @throws {@link KardApi.ForbiddenError}
     * @throws {@link KardApi.InvalidRequest}
     * @throws {@link KardApi.DoesNotExistError}
     * @throws {@link KardApi.InternalServerError}
     *
     * @example
     *     await client.organizations.contentStrategies.list("organizationId")
     */
    public list(
        organizationId: string,
        request: KardApi.organizations.ListContentStrategiesRequest = {},
        requestOptions?: ContentStrategiesClient.RequestOptions,
    ): core.HttpResponsePromise<KardApi.organizations.ContentStrategyListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(organizationId, request, requestOptions));
    }

    private async __list(
        organizationId: string,
        request: KardApi.organizations.ListContentStrategiesRequest = {},
        requestOptions?: ContentStrategiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<KardApi.organizations.ContentStrategyListResponse>> {
        const { "filter[name]": filterName, "page[after]": pageAfter, "page[size]": pageSize } = request;
        const _queryParams: Record<string, unknown> = {
            "filter[name]": filterName,
            "page[after]": pageAfter,
            "page[size]": pageSize,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KardApiEnvironment.Production,
                `v2/issuers/${core.url.encodePathParam(organizationId)}/contentStrategies`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as KardApi.organizations.ContentStrategyListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new KardApi.UnauthorizedError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new KardApi.ForbiddenError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 400:
                    throw new KardApi.InvalidRequest(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new KardApi.DoesNotExistError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new KardApi.InternalServerError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KardApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v2/issuers/{organizationId}/contentStrategies",
        );
    }

    /**
     * Retrieve a specific content strategy
     *
     * @param {string} organizationId - Unique identifier of the organization
     * @param {string} contentStrategyId - Unique identifier of the content strategy (UUID v7)
     * @param {ContentStrategiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link KardApi.UnauthorizedError}
     * @throws {@link KardApi.ForbiddenError}
     * @throws {@link KardApi.DoesNotExistError}
     * @throws {@link KardApi.InternalServerError}
     *
     * @example
     *     await client.organizations.contentStrategies.get("organizationId", "contentStrategyId")
     */
    public get(
        organizationId: string,
        contentStrategyId: string,
        requestOptions?: ContentStrategiesClient.RequestOptions,
    ): core.HttpResponsePromise<KardApi.organizations.ContentStrategyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(organizationId, contentStrategyId, requestOptions));
    }

    private async __get(
        organizationId: string,
        contentStrategyId: string,
        requestOptions?: ContentStrategiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<KardApi.organizations.ContentStrategyResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KardApiEnvironment.Production,
                `v2/issuers/${core.url.encodePathParam(organizationId)}/contentStrategies/${core.url.encodePathParam(contentStrategyId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as KardApi.organizations.ContentStrategyResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new KardApi.UnauthorizedError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new KardApi.ForbiddenError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new KardApi.DoesNotExistError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new KardApi.InternalServerError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KardApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v2/issuers/{organizationId}/contentStrategies/{contentStrategyId}",
        );
    }

    /**
     * Replace a content strategy. All fields must be provided; any omitted attribute is treated as cleared.
     *
     * @param {string} organizationId - Unique identifier of the organization
     * @param {string} contentStrategyId - Unique identifier of the content strategy (UUID v7)
     * @param {KardApi.organizations.UpdateContentStrategyRequestBody} request
     * @param {ContentStrategiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link KardApi.UnauthorizedError}
     * @throws {@link KardApi.ForbiddenError}
     * @throws {@link KardApi.InvalidRequest}
     * @throws {@link KardApi.ConflictError}
     * @throws {@link KardApi.DoesNotExistError}
     * @throws {@link KardApi.InternalServerError}
     *
     * @example
     *     await client.organizations.contentStrategies.update("organizationId", "contentStrategyId", {
     *         data: {
     *             type: "contentStrategy",
     *             attributes: {
     *                 name: "name",
     *                 categories: ["Arts & Entertainment", "Arts & Entertainment"],
     *                 categoryExclusions: ["Arts & Entertainment", "Arts & Entertainment"],
     *                 merchantExclusions: ["merchantExclusions", "merchantExclusions"]
     *             }
     *         }
     *     })
     */
    public update(
        organizationId: string,
        contentStrategyId: string,
        request: KardApi.organizations.UpdateContentStrategyRequestBody,
        requestOptions?: ContentStrategiesClient.RequestOptions,
    ): core.HttpResponsePromise<KardApi.organizations.ContentStrategyResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__update(organizationId, contentStrategyId, request, requestOptions),
        );
    }

    private async __update(
        organizationId: string,
        contentStrategyId: string,
        request: KardApi.organizations.UpdateContentStrategyRequestBody,
        requestOptions?: ContentStrategiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<KardApi.organizations.ContentStrategyResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KardApiEnvironment.Production,
                `v2/issuers/${core.url.encodePathParam(organizationId)}/contentStrategies/${core.url.encodePathParam(contentStrategyId)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as KardApi.organizations.ContentStrategyResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new KardApi.UnauthorizedError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new KardApi.ForbiddenError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 400:
                    throw new KardApi.InvalidRequest(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new KardApi.ConflictError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new KardApi.DoesNotExistError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new KardApi.InternalServerError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KardApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/v2/issuers/{organizationId}/contentStrategies/{contentStrategyId}",
        );
    }

    /**
     * Delete a content strategy. Returns 409 if the strategy is still referenced by another resource.
     *
     * @param {string} organizationId - Unique identifier of the organization
     * @param {string} contentStrategyId - Unique identifier of the content strategy (UUID v7)
     * @param {ContentStrategiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link KardApi.UnauthorizedError}
     * @throws {@link KardApi.ForbiddenError}
     * @throws {@link KardApi.ConflictError}
     * @throws {@link KardApi.DoesNotExistError}
     * @throws {@link KardApi.InternalServerError}
     *
     * @example
     *     await client.organizations.contentStrategies.delete("organizationId", "contentStrategyId")
     */
    public delete(
        organizationId: string,
        contentStrategyId: string,
        requestOptions?: ContentStrategiesClient.RequestOptions,
    ): core.HttpResponsePromise<KardApi.DeleteResourceResponse> {
        return core.HttpResponsePromise.fromPromise(this.__delete(organizationId, contentStrategyId, requestOptions));
    }

    private async __delete(
        organizationId: string,
        contentStrategyId: string,
        requestOptions?: ContentStrategiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<KardApi.DeleteResourceResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KardApiEnvironment.Production,
                `v2/issuers/${core.url.encodePathParam(organizationId)}/contentStrategies/${core.url.encodePathParam(contentStrategyId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as KardApi.DeleteResourceResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new KardApi.UnauthorizedError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new KardApi.ForbiddenError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new KardApi.ConflictError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new KardApi.DoesNotExistError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new KardApi.InternalServerError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KardApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/v2/issuers/{organizationId}/contentStrategies/{contentStrategyId}",
        );
    }
}
