// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * @example
 *     {
 *         data: {
 *             reverted: 5
 *         }
 *     }
 */
export interface RevertRewardsResponseObject {
    data: KardApi.RevertRewardsStats;
}
