// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../index.js";

/**
 * @example
 *     {
 *         "page[size]": 10,
 *         "filter[status]": "APPROVED",
 *         include: "merchant,offer"
 *     }
 */
export interface GetEarnedRewardsRequest {
    /** Cursor for next page (base64-encoded timestamp + transaction ID) */
    "page[after]"?: string;
    /** Cursor for previous page (base64-encoded timestamp + transaction ID) */
    "page[before]"?: string;
    /** Number of results per page */
    "page[size]"?: number;
    /** Filter by transaction status. Supported values are `APPROVED` and `SETTLED`. Defaults to `SETTLED` when omitted. When `APPROVED` is specified, only approved transactions that do not yet have a corresponding settled transaction are returned. */
    "filter[status]"?: KardApi.RewardedTransactionStatus;
    /** When `true`, return any matched transaction regardless of payment status. By default (`false`), only transactions that have been paid in full to the issuer (`paidToIssuer` is `PAID_IN_FULL`) are returned. This also controls whether unpaid transactions contribute to `lifetimeRewardsInCents`. Has no effect on `APPROVED` transactions, which are always returned when requested. */
    "filter[includeUnpaid]"?: boolean;
    /** Comma-separated list of related resources to include in the response. Supported values are `merchant` and `offer`. */
    include?: string;
}
