// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export interface InternalApiOfferAttribution {
    attributes: KardApi.InternalApiOfferAttributionAttributes;
    /** Kard-assigned ID of the resource */
    id?: string;
}
