// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import type * as KardApi from "../../../index.js";

export class CreateIncomingTransactionsMultiStatus extends errors.KardApiError {
    constructor(body: KardApi.TransactionsMultiResponse, rawResponse?: core.RawResponse) {
        super({
            message: "CreateIncomingTransactionsMultiStatus",
            statusCode: 207,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = this.constructor.name;
    }
}
