// This file was auto-generated by Fern from our API Definition.

/**
 * Attributes block for a `batchActivationSlot` resource.
 */
export interface BatchActivationSlotAttributes {
    /** Customer-defined alias for the slot, unique within the placement. */
    alias: string;
    /** Optional short description of the slot, limited to 50 characters. */
    shortDescription?: string | undefined;
}
