// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Relationship block for a `batchActivationSlot` resource.
 */
export interface BatchActivationSlotRelationships {
    /** Reference to the placement that fills this slot. The referenced placement provides the slot's content strategy and offer-count cap; request `?include=slots.placement` to embed it in `included`. */
    placement: KardApi.organizations.ToOneRelationship;
}
