// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Slot resource as it appears in the `included` array.
 */
export interface BatchActivationSlotInclusion {
    id: string;
    attributes: KardApi.organizations.BatchActivationSlotAttributes;
    relationships: KardApi.organizations.BatchActivationSlotRelationships;
}
