// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Cadence schedule for push notification placements
 */
export interface Cadence {
    /** Delivery frequency */
    frequency: KardApi.organizations.CadenceFrequency;
    /** Optional time of day in HH:mm format (24-hour, UTC) */
    timeOfDay?: string | undefined;
    /** Day of the week to deliver (used when frequency is WEEKLY, defaults to MON) */
    dayOfWeek?: KardApi.organizations.DayOfWeek | undefined;
    /** Day of the month to deliver, 1-31 (used when frequency is MONTHLY, defaults to 1) */
    dayOfMonth?: number | undefined;
}
