// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Content strategy as it appears in the `included` array.
 */
export interface ContentStrategyInclusion {
    id: string;
    attributes: KardApi.organizations.ContentStrategyAttributes;
}
