// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Attributes for creating a standard placement
 *
 * @example
 *     {
 *         name: "Homepage Banner",
 *         availableSlots: 5
 *     }
 */
export interface CreateStandardAttributes {
    /** Name of the placement */
    name: string;
    /** Placement status. Defaults to ACTIVE on create; when omitted on update, the current status is preserved. */
    status?: KardApi.organizations.PlacementStatus | undefined;
    /** Number of available slots (minimum 1) */
    availableSlots: number;
    /** ID of the content strategy to link this placement to */
    contentStrategyId?: string | undefined;
}
