// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Discriminated union for creating a placement
 */
export type CreatePlacementDataUnion =
    | KardApi.organizations.CreatePlacementDataUnion.PlacementMainPage
    | KardApi.organizations.CreatePlacementDataUnion.PlacementPushNotification
    | KardApi.organizations.CreatePlacementDataUnion.PlacementBatchActivation;

export namespace CreatePlacementDataUnion {
    export interface PlacementMainPage extends KardApi.organizations.CreateMainPagePlacementData {
        type: "placementMainPage";
    }

    export interface PlacementPushNotification extends KardApi.organizations.CreatePushNotificationPlacementData {
        type: "placementPushNotification";
    }

    export interface PlacementBatchActivation extends KardApi.organizations.CreateBatchActivationPlacementData {
        type: "placementBatchActivation";
    }
}
