// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Attributes for creating a group placement
 *
 * @example
 *     {
 *         name: "Seasonal Collection",
 *         slots: [{
 *                 placementId: "01961e5a-f26f-7e44-ce5f-1ad7c9fb4e67",
 *                 alias: "primary",
 *                 shortDescription: "Seasonal picks"
 *             }]
 *     }
 */
export interface CreateGroupAttributes {
    /** Name of the placement */
    name: string;
    /** Slots that make up the group */
    slots: KardApi.organizations.CreateBatchActivationSlot[];
}
