// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Attributes for creating a push-notification placement
 *
 * @example
 *     {
 *         name: "Push Alert",
 *         cadence: {
 *             frequency: KardApi.organizations.CadenceFrequency.Daily,
 *             timeOfDay: "09:00"
 *         }
 *     }
 */
export interface CreatePushNotificationAttributes {
    /** Name of the placement */
    name: string;
    /** Placement status. Defaults to ACTIVE on create; when omitted on update, the current status is preserved. */
    status?: KardApi.organizations.PlacementStatus | undefined;
    /** Delivery cadence for the notification */
    cadence: KardApi.organizations.Cadence;
    /** ID of the content strategy to link this placement to */
    contentStrategyId?: string | undefined;
}
