// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Data for creating a main-page placement
 */
export interface CreateMainPagePlacementData {
    /** Main-page placement attributes for creation */
    attributes: KardApi.organizations.CreateMainPageAttributes;
}
