// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Request body for creating a placement
 *
 * @example
 *     {
 *         data: {
 *             type: "placementMainPage",
 *             attributes: {
 *                 name: "Homepage Banner",
 *                 availableSlots: 5
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         data: {
 *             type: "placementPushNotification",
 *             attributes: {
 *                 name: "Daily Deal Alert",
 *                 cadence: {
 *                     frequency: KardApi.organizations.CadenceFrequency.Daily,
 *                     timeOfDay: "09:00"
 *                 }
 *             }
 *         }
 *     }
 */
export interface CreatePlacementRequestBody {
    /** Placement data for creation */
    data: KardApi.organizations.CreatePlacementDataUnion;
}
