// This file was auto-generated by Fern from our API Definition.

/**
 * Attributes for creating a standard placement
 *
 * @example
 *     {
 *         name: "Homepage Banner",
 *         availableSlots: 5
 *     }
 */
export interface CreateStandardAttributes {
    /** Name of the placement */
    name: string;
    /** Cardholder-facing title for the section (minimum 1 character). Omit to let clients use their default label. */
    displayName?: string | undefined;
    /** Number of available slots (minimum 1) */
    availableSlots: number;
    /** ID of the content strategy to link this placement to */
    contentStrategyId?: string | undefined;
}
