// This file was auto-generated by Fern from our API Definition.

/** Day of the week (used when frequency is WEEKLY) */
export const DayOfWeek = {
    Mon: "MON",
    Tue: "TUE",
    Wed: "WED",
    Thu: "THU",
    Fri: "FRI",
    Sat: "SAT",
    Sun: "SUN",
} as const;
export type DayOfWeek = (typeof DayOfWeek)[keyof typeof DayOfWeek];
