// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Single placement document, optionally with embedded related resources
 */
export interface PlacementResource {
    /** Placement resource */
    data: KardApi.organizations.PlacementFormatUnion;
    /** Related resources requested via the `include` query parameter. Only populated when `include=contentStrategy` is supplied and the placement is linked to a content strategy. */
    included?: KardApi.organizations.ContentStrategyResponse[] | undefined;
}
