// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Push-notification placement resource data
 */
export interface PushNotificationPlacementData {
    /** Unique identifier of the placement (UUID v7) */
    id: string;
    attributes: KardApi.organizations.PushNotificationPlacementAttributes;
}
