// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Attributes for a push-notification placement
 */
export interface PushNotificationPlacementAttributes {
    /** Name of the placement */
    name: string;
    /** ID of the organization this placement belongs to */
    organizationId: string;
    /** Delivery cadence for the notification */
    cadence: KardApi.organizations.Cadence;
    /** When the placement was created (ISO 8601 UTC) */
    createdAt: string;
    /** When the placement was last modified (ISO 8601 UTC) */
    lastModified: string;
}
