// This file was auto-generated by Fern from our API Definition.

/**
 * A reference to another resource by type and id.
 */
export interface ResourceIdentifier {
    /** Discriminant of the referenced resource (e.g. `contentStrategy`). */
    type: string;
    /** Identifier of the referenced resource. */
    id: string;
}
