// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * A JSON:API to-many relationship payload.
 */
export interface ToManyRelationship {
    /** The linked resource identifiers. */
    data: KardApi.organizations.ResourceIdentifier[];
}
