// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Attributes for updating a group placement. All fields are required.
 *
 * @example
 *     {
 *         name: "Updated Collection",
 *         slots: [{
 *                 slotId: "01961e5a-b59c-7f77-9d8c-4d0af3ce7b9a",
 *                 placementId: "01961e5a-f26f-7e44-ce5f-1ad7c9fb4e67",
 *                 alias: "primary",
 *                 shortDescription: "Seasonal picks"
 *             }]
 *     }
 */
export interface UpdateGroupAttributes {
    /** Name of the placement */
    name: string;
    /** Slots that make up the group. Slots present in the prior state but absent from this list are removed. */
    slots: KardApi.organizations.UpdateBatchActivationSlot[];
}
