// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Discriminated union for updating a placement
 */
export type UpdatePlacementDataUnion =
    | KardApi.organizations.UpdatePlacementDataUnion.PlacementMainPage
    | KardApi.organizations.UpdatePlacementDataUnion.PlacementPushNotification;

export namespace UpdatePlacementDataUnion {
    export interface PlacementMainPage extends KardApi.organizations.UpdateMainPagePlacementData {
        type: "placementMainPage";
    }

    export interface PlacementPushNotification extends KardApi.organizations.UpdatePushNotificationPlacementData {
        type: "placementPushNotification";
    }
}
