// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Data for updating a group placement
 */
export interface UpdateGroupPlacementData {
    /** Group placement attributes for update */
    attributes: KardApi.organizations.UpdateGroupAttributes;
}
