// This file was auto-generated by Fern from our API Definition.

/**
 * Attributes for updating a main-page placement. All fields are required.
 *
 * @example
 *     {
 *         name: "Updated Banner",
 *         availableSlots: 10
 *     }
 */
export interface UpdateMainPageAttributes {
    /** Name of the placement */
    name: string;
    /** Number of available slots (minimum 1) */
    availableSlots: number;
    /** ID of the content strategy to link this placement to. Omit to clear any existing link (PUT requires the full attribute set, so a missing value unlinks the placement). */
    contentStrategyId?: string | undefined;
}
