// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as KardApi from "../../../../../index.js";

export declare namespace ChildrenClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ChildrenClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ChildrenClient.Options>;

    constructor(options: ChildrenClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List child organizations belonging to the authenticated issuer
     *
     * @param {string} organizationId - Unique identifier of the parent organization
     * @param {KardApi.organizations.ListChildrenRequest} request
     * @param {ChildrenClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link KardApi.UnauthorizedError}
     * @throws {@link KardApi.ForbiddenError}
     * @throws {@link KardApi.DoesNotExistError}
     * @throws {@link KardApi.InternalServerError}
     *
     * @example
     *     await client.organizations.children.list("organizationId")
     */
    public list(
        organizationId: string,
        request: KardApi.organizations.ListChildrenRequest = {},
        requestOptions?: ChildrenClient.RequestOptions,
    ): core.HttpResponsePromise<KardApi.organizations.ChildOrganizationListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(organizationId, request, requestOptions));
    }

    private async __list(
        organizationId: string,
        request: KardApi.organizations.ListChildrenRequest = {},
        requestOptions?: ChildrenClient.RequestOptions,
    ): Promise<core.WithRawResponse<KardApi.organizations.ChildOrganizationListResponse>> {
        const { "page[after]": pageAfter, "page[size]": pageSize } = request;
        const _queryParams: Record<string, unknown> = {
            "page[after]": pageAfter,
            "page[size]": pageSize,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KardApiEnvironment.Production,
                `v2/issuers/${core.url.encodePathParam(organizationId)}/children`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as KardApi.organizations.ChildOrganizationListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new KardApi.UnauthorizedError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new KardApi.ForbiddenError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new KardApi.DoesNotExistError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new KardApi.InternalServerError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KardApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v2/issuers/{organizationId}/children",
        );
    }

    /**
     * Create a child organization by cloning the parent and overriding specified fields. An 8-digit numeric ID is generated automatically. The name is required, must be uppercase, and must not contain spaces.
     *
     * @param {string} organizationId - Unique identifier of the parent organization
     * @param {KardApi.organizations.CreateChildRequestBody} request
     * @param {ChildrenClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link KardApi.UnauthorizedError}
     * @throws {@link KardApi.ForbiddenError}
     * @throws {@link KardApi.InvalidRequest}
     * @throws {@link KardApi.ConflictError}
     * @throws {@link KardApi.InternalServerError}
     *
     * @example
     *     await client.organizations.children.create("organizationId", {
     *         data: {
     *             type: "organization",
     *             attributes: {
     *                 name: "name"
     *             }
     *         }
     *     })
     */
    public create(
        organizationId: string,
        request: KardApi.organizations.CreateChildRequestBody,
        requestOptions?: ChildrenClient.RequestOptions,
    ): core.HttpResponsePromise<KardApi.organizations.ChildOrganizationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(organizationId, request, requestOptions));
    }

    private async __create(
        organizationId: string,
        request: KardApi.organizations.CreateChildRequestBody,
        requestOptions?: ChildrenClient.RequestOptions,
    ): Promise<core.WithRawResponse<KardApi.organizations.ChildOrganizationResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KardApiEnvironment.Production,
                `v2/issuers/${core.url.encodePathParam(organizationId)}/children`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as KardApi.organizations.ChildOrganizationResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new KardApi.UnauthorizedError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new KardApi.ForbiddenError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 400:
                    throw new KardApi.InvalidRequest(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new KardApi.ConflictError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new KardApi.InternalServerError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KardApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v2/issuers/{organizationId}/children",
        );
    }

    /**
     * Retrieve a specific child organization
     *
     * @param {string} organizationId - Unique identifier of the parent organization
     * @param {string} childId - Unique identifier of the child organization
     * @param {ChildrenClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link KardApi.UnauthorizedError}
     * @throws {@link KardApi.ForbiddenError}
     * @throws {@link KardApi.DoesNotExistError}
     * @throws {@link KardApi.InternalServerError}
     *
     * @example
     *     await client.organizations.children.get("organizationId", "childId")
     */
    public get(
        organizationId: string,
        childId: string,
        requestOptions?: ChildrenClient.RequestOptions,
    ): core.HttpResponsePromise<KardApi.organizations.ChildOrganizationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(organizationId, childId, requestOptions));
    }

    private async __get(
        organizationId: string,
        childId: string,
        requestOptions?: ChildrenClient.RequestOptions,
    ): Promise<core.WithRawResponse<KardApi.organizations.ChildOrganizationResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KardApiEnvironment.Production,
                `v2/issuers/${core.url.encodePathParam(organizationId)}/children/${core.url.encodePathParam(childId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as KardApi.organizations.ChildOrganizationResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new KardApi.UnauthorizedError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new KardApi.ForbiddenError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new KardApi.DoesNotExistError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new KardApi.InternalServerError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KardApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v2/issuers/{organizationId}/children/{childId}",
        );
    }

    /**
     * Update a child organization. Only the name can be changed.
     *
     * @param {string} organizationId - Unique identifier of the parent organization
     * @param {string} childId - Unique identifier of the child organization
     * @param {KardApi.organizations.UpdateChildRequestBody} request
     * @param {ChildrenClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link KardApi.UnauthorizedError}
     * @throws {@link KardApi.ForbiddenError}
     * @throws {@link KardApi.InvalidRequest}
     * @throws {@link KardApi.DoesNotExistError}
     * @throws {@link KardApi.InternalServerError}
     *
     * @example
     *     await client.organizations.children.update("organizationId", "childId", {
     *         data: {
     *             type: "organization",
     *             attributes: {}
     *         }
     *     })
     */
    public update(
        organizationId: string,
        childId: string,
        request: KardApi.organizations.UpdateChildRequestBody,
        requestOptions?: ChildrenClient.RequestOptions,
    ): core.HttpResponsePromise<KardApi.organizations.ChildOrganizationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(organizationId, childId, request, requestOptions));
    }

    private async __update(
        organizationId: string,
        childId: string,
        request: KardApi.organizations.UpdateChildRequestBody,
        requestOptions?: ChildrenClient.RequestOptions,
    ): Promise<core.WithRawResponse<KardApi.organizations.ChildOrganizationResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KardApiEnvironment.Production,
                `v2/issuers/${core.url.encodePathParam(organizationId)}/children/${core.url.encodePathParam(childId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as KardApi.organizations.ChildOrganizationResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new KardApi.UnauthorizedError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new KardApi.ForbiddenError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 400:
                    throw new KardApi.InvalidRequest(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new KardApi.DoesNotExistError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new KardApi.InternalServerError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KardApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/v2/issuers/{organizationId}/children/{childId}",
        );
    }

    /**
     * Delete a child organization
     *
     * @param {string} organizationId - Unique identifier of the parent organization
     * @param {string} childId - Unique identifier of the child organization
     * @param {ChildrenClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link KardApi.UnauthorizedError}
     * @throws {@link KardApi.ForbiddenError}
     * @throws {@link KardApi.DoesNotExistError}
     * @throws {@link KardApi.InternalServerError}
     *
     * @example
     *     await client.organizations.children.delete("organizationId", "childId")
     */
    public delete(
        organizationId: string,
        childId: string,
        requestOptions?: ChildrenClient.RequestOptions,
    ): core.HttpResponsePromise<KardApi.DeleteResourceResponse> {
        return core.HttpResponsePromise.fromPromise(this.__delete(organizationId, childId, requestOptions));
    }

    private async __delete(
        organizationId: string,
        childId: string,
        requestOptions?: ChildrenClient.RequestOptions,
    ): Promise<core.WithRawResponse<KardApi.DeleteResourceResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KardApiEnvironment.Production,
                `v2/issuers/${core.url.encodePathParam(organizationId)}/children/${core.url.encodePathParam(childId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as KardApi.DeleteResourceResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new KardApi.UnauthorizedError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new KardApi.ForbiddenError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new KardApi.DoesNotExistError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new KardApi.InternalServerError(
                        _response.error.body as KardApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KardApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/v2/issuers/{organizationId}/children/{childId}",
        );
    }
}
