// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetOffersByPlacementRequest {
    /** Case-insensitive search string to filter offers by merchant name */
    "filter[search]"?: string;
    "filter[purchaseChannel]"?: KardApi.PurchaseChannel[];
    "filter[category]"?: KardApi.CategoryOption;
    "filter[isTargeted]"?: boolean;
    /** CSV list of included resources in the response (e.g "categories"). Allowed value is `categories`. */
    include?: string | string[];
    /** UI component types to include in the response. */
    supportedComponents?: KardApi.users.ComponentType | KardApi.users.ComponentType[];
}
