// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

export type ActivateOfferIncluded = KardApi.users.OfferDataUnion | KardApi.users.CategoryIncluded;
