// This file was auto-generated by Fern from our API Definition.

/** Options for what to include in the activate offer response */
export const ActivateOfferIncludeOption = {
    Offer: "offer",
} as const;
export type ActivateOfferIncludeOption = (typeof ActivateOfferIncludeOption)[keyof typeof ActivateOfferIncludeOption];
