// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

export interface AttributionState {
    /** The position of the offer in the list shown to the user (1-indexed) */
    rank?: number;
    /** The active filters when the user saw the offer */
    filters?: KardApi.users.AttributionFilter[];
}
