// This file was auto-generated by Fern from our API Definition.

/** Options for what to include in the boost offer response */
export const BoostOfferIncludeOption = {
    Offer: "offer",
} as const;
export type BoostOfferIncludeOption = (typeof BoostOfferIncludeOption)[keyof typeof BoostOfferIncludeOption];
