// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

export type CreateAttributionRequestUnion =
    | KardApi.users.CreateAttributionRequestUnion.OfferAttribution
    | KardApi.users.CreateAttributionRequestUnion.NotificationAttribution
    | KardApi.users.CreateAttributionRequestUnion.PlacementSlotAttribution;

export namespace CreateAttributionRequestUnion {
    export interface OfferAttribution extends KardApi.users.OfferAttributionRequest {
        type: "offerAttribution";
    }

    export interface NotificationAttribution extends KardApi.users.NotificationAttributionRequest {
        type: "notificationAttribution";
    }

    export interface PlacementSlotAttribution extends KardApi.users.PlacementSlotAttributionRequest {
        type: "placementSlotAttribution";
    }
}
