// This file was auto-generated by Fern from our API Definition.

/** Where the notification attribution event is taking place in your rewards experience. */
export const NotificationMedium = {
    Push: "PUSH",
} as const;
export type NotificationMedium = (typeof NotificationMedium)[keyof typeof NotificationMedium];
