// This file was auto-generated by Fern from our API Definition.

/** Where the offer attribution event is taking place in your rewards experience. */
export const OfferMedium = {
    Browse: "BROWSE",
    Email: "EMAIL",
    Map: "MAP",
    Search: "SEARCH",
    Cta: "CTA",
} as const;
export type OfferMedium = (typeof OfferMedium)[keyof typeof OfferMedium];
