/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KardApi from "../../../../../index.js";

export type SubscriptionRequestUnion = KardApi.notifications.SubscriptionRequestUnion.Subscription;

export namespace SubscriptionRequestUnion {
    export interface Subscription extends KardApi.notifications.SubscriptionRequest {
        type: "subscription";
    }
}
