// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

export interface SubscriptionRequestAttributes {
    /** The name of the event for the subscription */
    eventName: KardApi.NotificationType;
    /** The URL where notifications will be delivered */
    webhookUrl: string;
    /** Indicates whether the subscription is active */
    enabled: boolean;
}
