// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

export type SubscriptionUnion = KardApi.notifications.SubscriptionUnion.Subscription;

export namespace SubscriptionUnion {
    export interface Subscription extends KardApi.notifications.Subscription {
        type: "subscription";
    }
}
