// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * @example
 *     {
 *         data: {
 *             type: "subscription",
 *             id: "0193i257-014e-7dd2-9455-fb964d9c85cr",
 *             attributes: {
 *                 eventName: KardApi.NotificationType.EarnedRewardApproved,
 *                 webhookUrl: "https://webhookUrl.com/post",
 *                 enabled: true
 *             }
 *         }
 *     }
 */
export interface UpdateSubscriptionsResponseObject {
    data: KardApi.notifications.CreateSubscriptionUnion;
}
