// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export interface CommissionEarnedDetails {
    issuer: KardApi.CommissionValue;
    user: KardApi.CommissionValue;
}
