// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export type CreateAuditRequestDataUnion = KardApi.CreateAuditRequestDataUnion.Audit;

export namespace CreateAuditRequestDataUnion {
    export interface Audit extends KardApi.AuditRequestData {
        type: "audit";
    }
}
