// This file was auto-generated by Fern from our API Definition.

export interface CreateFileUploadAttributes {
    /** Name of the file to upload, including extension (e.g. "transaction_12345.jsonl") */
    filename: string;
}
