// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * @example
 *     {
 *         data: [{
 *                 type: "audit",
 *                 attributes: {
 *                     auditCode: 8001,
 *                     merchantName: "Caribbean Goodness",
 *                     auditDescription: "duplicate transaction",
 *                     transactionId: "issuerTransaction123"
 *                 }
 *             }]
 *     }
 */
export interface CreateAuditRequestBody {
    data: KardApi.CreateAuditRequestDataUnion[];
}
