// This file was auto-generated by Fern from our API Definition.

/** Time window for earned rewards queries, ending now. `YTD` starts at January 1 of the current year (UTC). */
export const EarnedRewardsRange = {
    Last12Months: "12M",
    Last6Months: "6M",
    Last3Months: "3M",
    YearToDate: "YTD",
} as const;
export type EarnedRewardsRange = (typeof EarnedRewardsRange)[keyof typeof EarnedRewardsRange];
