// This file was auto-generated by Fern from our API Definition.

export interface FinancialInstitution {
    /** Research, Statistics, Supervision, Discount ID (RSSD) - Federal Reserve identifier for financial institutions */
    rssdId: string;
    /** Name of the financial institution */
    name: string;
}
