// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export interface FraudulentTransactionData {
    /** transactionId of the fraudulent transaction */
    id: string;
    /** only value allowed is "fraudulentTransaction" */
    type: string;
    attributes: KardApi.FraudulentTransactionAttributes;
}
