// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * @example
 *     {
 *         data: [{
 *                 type: "fraudulentTransaction",
 *                 id: "myTxnId123",
 *                 attributes: {
 *                     userId: "user123"
 *                 }
 *             }]
 *     }
 */
export interface FraudulentTransactionObject {
    data: KardApi.FraudulentTransactionData[];
}
