// This file was auto-generated by Fern from our API Definition.

export interface GetEarnedRewardsMeta {
    /** Lifetime rewards earned by the user across matched transactions in cents. By default all matched transactions are included regardless of payment status; pass `filter[paidInFullOnly]=true` to restrict the total to transactions paid in full to the issuer (`paidToIssuer` is `PAID_IN_FULL`). */
    lifetimeRewardsInCents: number;
}
