/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KardApi from "../../../index.js";

export interface MatchedTransactionsAttributes {
    /** The ID of the user as defined on the issuers system */
    userId: string;
    /** Transaction amount in cents */
    amount: number;
    /** The base amount in cents excluding additional charges (such as tips, taxes, and other fees). */
    subtotal?: number;
    /** Description of transaction - usually includes merchant and other key details on transaction */
    description: string;
    /** Timestamp for <b>APPROVED</b> transaction event; <b>REQUIRED</b> for transactions with <b>APPROVED</b> status, and <b>HIGHLY RECOMMENDED</b> to include for transactions with a <b>SETTLED</b> status. Date string should be in ISO format i.e.`'YYYY-MM-DDThh:mm:ss.sTZD'` where TZD = time zone designator (Z or +hh:mm or -hh:mm) i.e. `1994-11-05T08:15:30-05:00 OR 1994-11-05T08:15:30Z` */
    authorizationDate: string;
    /** The ID of the Kard offer that the transaction matched to. If this field is omitted, the transaction will be treated as not matched to any Kard offer. */
    matchedOfferId?: string;
    /** The unique Kard location ID where the transaction took place. */
    matchedLocationId?: string;
    /** Merchant details */
    merchant?: KardApi.Merchant;
    /** The type of payment involved in the transaction. */
    paymentType: KardApi.PaymentType;
    /** Bank identification number (BIN). Must be a valid BIN of 6 digits. If over 6 digits, please send first 6. */
    cardBIN?: string;
    /** Card last four digits. This field is **required** when `paymentType` is `CARD`. */
    cardLastFour?: string;
    /** Transaction approval code */
    authorizationCode?: string;
    /** Retrieval Reference Number */
    retrievalReferenceNumber?: string;
    /** System Trace Audit Number */
    systemTraceAuditNumber?: string;
    /** Acquirer Reference Number */
    acquirerReferenceNumber?: string;
    /** The direction in which the funds flow - DEBIT or CREDIT */
    direction: KardApi.DirectionType;
    /** The card network associated with the transaction */
    cardNetwork?: KardApi.CardNetwork;
    /** The transaction ID */
    transactionId: string;
    /** The card product ID associated with the transaction */
    cardProductId?: string;
}
