// This file was auto-generated by Fern from our API Definition.

export const PaymentType = {
    Card: "CARD",
    Cash: "CASH",
    Unknown: "UNKNOWN",
} as const;
export type PaymentType = (typeof PaymentType)[keyof typeof PaymentType];
