/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PaymentType = "CARD" | "CASH" | "UNKNOWN";
export const PaymentType = {
    Card: "CARD",
    Cash: "CASH",
    Unknown: "UNKNOWN",
} as const;
