// This file was auto-generated by Fern from our API Definition.

export const ReceiptMediumType = {
    Electronic: "ELECTRONIC",
    Physical: "PHYSICAL",
} as const;
export type ReceiptMediumType = (typeof ReceiptMediumType)[keyof typeof ReceiptMediumType];
