// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export interface RewardedTransactionRelationships {
    user: KardApi.RelationshipSingle;
    merchant: KardApi.RelationshipSingle;
    offer: KardApi.RelationshipSingle;
}
