// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export type RewardedTransactionUnion =
    | KardApi.RewardedTransactionUnion.RewardedTransaction
    | KardApi.RewardedTransactionUnion.ApprovedTransaction;

export namespace RewardedTransactionUnion {
    export interface RewardedTransaction extends KardApi.RewardedTransaction {
        type: "rewardedTransaction";
    }

    export interface ApprovedTransaction extends KardApi.ApprovedTransaction {
        type: "approvedTransaction";
    }
}
