// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export interface RewardedTransaction {
    /** Unique transaction identifier */
    id: string;
    attributes: KardApi.RewardedTransactionAttributes;
    relationships: KardApi.RewardedTransactionRelationships;
}
