// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export interface RewardedTransactionAttributes {
    /** Status of the rewarded transaction */
    status: KardApi.RewardedTransactionStatus;
    /** The transaction identifier */
    transactionId: string;
    /** Transaction amount in cents */
    transactionAmountInCents: number;
    /** Timestamp of the transaction in ISO 8601 format */
    transactionTimestamp: string;
    /** Payment status to issuer */
    paidToIssuer: KardApi.PaymentStatus;
    commissionEarned: KardApi.CommissionEarnedDetails;
    /** Timestamp representing the month when the transaction has been paid out to issuer */
    payoutTimestamp?: string;
    /** Bank identification number (BIN). */
    cardBIN?: string;
    /** Card last four digits. */
    cardLastFour?: string;
}
