// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * @example
 *     {
 *         data: {
 *             type: "job",
 *             id: "c94a93a7-beb9-4e58-960c-2c812f849398",
 *             attributes: {
 *                 status: KardApi.JobStatus.Queued,
 *                 message: "Incoming Transactions event successfully queued for processing"
 *             }
 *         }
 *     }
 */
export interface TransactionsResponse {
    data: KardApi.TransactionsResponseData;
}
