/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TransactionStatus = "APPROVED" | "SETTLED" | "REVERSED" | "RETURNED" | "DECLINED";
export const TransactionStatus = {
    Approved: "APPROVED",
    Settled: "SETTLED",
    Reversed: "REVERSED",
    Returned: "RETURNED",
    Declined: "DECLINED",
} as const;
