/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KardApi from "../../../index.js";

export interface TransactionsResponseData {
    type: KardApi.ResourceType;
    /** The request id of the pending job */
    id: string;
    attributes: KardApi.Job;
}
