// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Paginated list of child organizations
 */
export interface ChildOrganizationListResponse {
    /** Array of child organization resources */
    data: KardApi.organizations.ChildOrganizationResponse[];
    links?: KardApi.Links | undefined;
    /** Pagination metadata */
    meta?: KardApi.OrganizationPaginationMetadata | undefined;
}
