// This file was auto-generated by Fern from our API Definition.

/** Available button styles for CTA components */
export const ButtonStyle = {
    Primary: "PRIMARY",
    Disabled: "DISABLED",
} as const;
export type ButtonStyle = (typeof ButtonStyle)[keyof typeof ButtonStyle];
