// This file was auto-generated by Fern from our API Definition.

/**
 * Action configuration for CTA button
 */
export interface CtaAction {
    /** URL endpoint to call when button is clicked */
    url: string;
    /** HTTP method to use (e.g., POST) */
    method: string;
}
