// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Call-to-action button component for offers
 */
export interface CtaComponent {
    /** Text to display on the button */
    buttonText: string;
    /** Style of the button */
    buttonStyle: KardApi.users.ButtonStyle;
}
