// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * @example
 *     {
 *         data: [{
 *                 type: "location",
 *                 id: "5e27318c9b346f00087fba8l",
 *                 attributes: {
 *                     name: "Worlds Greatest Chicken",
 *                     address: {
 *                         street: "120 Main St",
 *                         city: "Philadelphia",
 *                         state: "PA",
 *                         zipCode: "19147"
 *                     },
 *                     coordinates: {
 *                         longitude: -75.1446869,
 *                         latitude: 39.9419429
 *                     },
 *                     phone: "+1 (123) 555-8880",
 *                     operationHours: {
 *                         periods: [{
 *                                 close: {
 *                                     day: 1,
 *                                     time: "1700"
 *                                 },
 *                                 open: {
 *                                     day: 1,
 *                                     time: "0900"
 *                                 }
 *                             }, {
 *                                 close: {
 *                                     day: 2,
 *                                     time: "1700"
 *                                 },
 *                                 open: {
 *                                     day: 2,
 *                                     time: "0900"
 *                                 }
 *                             }, {
 *                                 close: {
 *                                     day: 3,
 *                                     time: "1700"
 *                                 },
 *                                 open: {
 *                                     day: 3,
 *                                     time: "0900"
 *                                 }
 *                             }, {
 *                                 close: {
 *                                     day: 4,
 *                                     time: "1700"
 *                                 },
 *                                 open: {
 *                                     day: 4,
 *                                     time: "0900"
 *                                 }
 *                             }, {
 *                                 close: {
 *                                     day: 5,
 *                                     time: "1700"
 *                                 },
 *                                 open: {
 *                                     day: 5,
 *                                     time: "0900"
 *                                 }
 *                             }],
 *                         weekdayText: ["Monday: 9:00 AM \u2013 5:00 PM", "Tuesday: 9:00 AM \u2013 5:00 PM", "Wednesday: 9:00 AM \u2013 5:00 PM", "Thursday: 9:00 AM \u2013 5:00 PM", "Friday: 9:00 AM \u2013 5:00 PM", "Saturday: Closed", "Sunday: Closed"]
 *                     }
 *                 },
 *                 relationships: {
 *                     offers: {
 *                         data: [{
 *                                 type: "standardOffer",
 *                                 id: "5e27318c9b346f00087fbb5b"
 *                             }]
 *                     },
 *                     category: {
 *                         data: [{
 *                                 type: "category",
 *                                 id: "65920081b524d126068de24a"
 *                             }]
 *                     }
 *                 }
 *             }],
 *         included: [{
 *                 type: "category",
 *                 id: "65920081b524d126068de24a",
 *                 attributes: {
 *                     name: KardApi.CategoryOption.FoodBeverage
 *                 }
 *             }, {
 *                 type: "standardOffer",
 *                 id: "5e27318c9b346f00087fbb5c",
 *                 attributes: {
 *                     name: "Worlds Greatest Chicken",
 *                     terms: "Worlds Greatest Chicken offers are only available within US Locations.",
 *                     purchaseChannel: [KardApi.PurchaseChannel.Instore],
 *                     userReward: {
 *                         type: KardApi.CommissionType.Percent,
 *                         value: 5.7
 *                     },
 *                     startDate: "2022-01-01T05:00:00Z",
 *                     expirationDate: "2022-01-01T05:00:00Z",
 *                     minRewardAmount: {
 *                         type: KardApi.users.AmountType.Cents,
 *                         value: 500
 *                     },
 *                     maxRewardAmount: {
 *                         type: KardApi.users.AmountType.Cents,
 *                         value: 2000
 *                     },
 *                     minTransactionAmount: {
 *                         type: KardApi.users.AmountType.Cents,
 *                         value: 500
 *                     },
 *                     maxTransactionAmount: {
 *                         type: KardApi.users.AmountType.Cents,
 *                         value: 2000
 *                     },
 *                     maxRedemptions: 1,
 *                     isTargeted: true,
 *                     assets: [{
 *                             type: "IMG_VIEW",
 *                             url: "http://assets.getkard.com/logo/img?attribution-tokens",
 *                             alt: "Worlds Greatest Chicken Logo Image"
 *                         }, {
 *                             type: "BANNER_VIEW",
 *                             url: "http://assets.getkard.com/banner/img?attribution-tokens",
 *                             alt: "Worlds Greatest Chicken Banner Image"
 *                         }],
 *                     websiteUrl: "http://worldsgreatestchickent.test.com",
 *                     description: "Worlds Greatest Chicken brings you the tastiest crispy, double fried spicy chicken in the world."
 *                 }
 *             }],
 *         links: {
 *             self: "/v2/issuers/{organizationId}/users/{userId}/locations?page[size]=1&filter[latitude]=39.9419429&filter[longitude]=-75.1446869&filter[radius]=10&include=offers,categories",
 *             next: "/v2/issuers/{organizationId}/users/{userId}/locations?page[after]=NDMyNzQyODI3OTQw&page[size]=1&filter[latitude]=39.9419429&filter[longitude]=-75.1446869&filter[radius]=10&include=offers,categories"
 *         }
 *     }
 */
export interface LocationsResponseObject {
    data: KardApi.users.LocationData[];
    links: KardApi.Links;
    included?: KardApi.users.EligibilityLocationIncluded[];
}
