// This file was auto-generated by Fern from our API Definition.

export const LocationPartnerIdType = {
    Google: "google",
} as const;
export type LocationPartnerIdType = (typeof LocationPartnerIdType)[keyof typeof LocationPartnerIdType];
