// This file was auto-generated by Fern from our API Definition.

export const LocationSortOptions = {
    LocationNameAsc: "locationName",
    LocationNameDesc: "-locationName",
} as const;
export type LocationSortOptions = (typeof LocationSortOptions)[keyof typeof LocationSortOptions];
