// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

export interface LocationData {
    type: "location";
    /** Location ID in Kard's system */
    id: KardApi.MongoId;
    attributes: KardApi.users.LocationAttributes;
    /** Related resources to the offer */
    relationships?: KardApi.users.LocationRelationships;
}
