// This file was auto-generated by Fern from our API Definition.

/** Available border color options for logo flare */
export const LogoFlareBorderColor = {
    Primary: "PRIMARY",
    Secondary: "SECONDARY",
} as const;
export type LogoFlareBorderColor = (typeof LogoFlareBorderColor)[keyof typeof LogoFlareBorderColor];
