// This file was auto-generated by Fern from our API Definition.

/** Available positions for the logo flare badge */
export const LogoFlareBadgePosition = {
    TopRight: "TOP_RIGHT",
    TopLeft: "TOP_LEFT",
    BottomRight: "BOTTOM_RIGHT",
    BottomLeft: "BOTTOM_LEFT",
} as const;
export type LogoFlareBadgePosition = (typeof LogoFlareBadgePosition)[keyof typeof LogoFlareBadgePosition];
