/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KardApi from "../../../../../index.js";

export type OfferDataUnion = KardApi.users.OfferDataUnion.StandardOffer;

export namespace OfferDataUnion {
    export interface StandardOffer extends KardApi.users.StandardOffer {
        type: "standardOffer";
    }
}
