// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Metadata about the full result set across all pages
 */
export interface OffersMeta {
    /** All distinct categories available across the entire filtered result set, not just the current page */
    availableCategories?: KardApi.users.CategoryIncluded[] | undefined;
}
