// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * @example
 *     {
 *         data: [{
 *                 type: "standardOffer",
 *                 id: "5e27318c9b346f00087fbb5c",
 *                 attributes: {
 *                     name: "Worlds Greatest Chicken",
 *                     terms: "Worlds Greatest Chicken offers are only available within US Locations.",
 *                     purchaseChannel: [KardApi.PurchaseChannel.Instore],
 *                     userReward: {
 *                         type: KardApi.CommissionType.Percent,
 *                         value: 5.7
 *                     },
 *                     startDate: "2024-11-17T05:00:00Z",
 *                     expirationDate: "2025-03-17T05:00:00Z",
 *                     minRewardAmount: {
 *                         type: KardApi.users.AmountType.Cents,
 *                         value: 500
 *                     },
 *                     maxRewardAmount: {
 *                         type: KardApi.users.AmountType.Cents,
 *                         value: 2000
 *                     },
 *                     minTransactionAmount: {
 *                         type: KardApi.users.AmountType.Cents,
 *                         value: 500
 *                     },
 *                     maxTransactionAmount: {
 *                         type: KardApi.users.AmountType.Cents,
 *                         value: 10000
 *                     },
 *                     maxRedemptions: 1,
 *                     isTargeted: true,
 *                     assets: [{
 *                             url: "http://attribution.getkard.com/logos/breakfastbunny_logo.png?subtype=IMG_VIEW&offerId=629fc220b7a4290009a188ec&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWZlcnJpbmdQYXJ0bmVyVXNlcklkIjoiNDM4MTAzIiwiaXNzdWVySWQiOiIwMDAwNDMyMSIsInR5cGUiOiJPRkZFUiIsInBheWxvYWQiOnsiand0VGltZXN0YW1wIjoiMjAyNi0wNC0yMyJ9fQ.4f9QmoGpgXVIXu9Tq8XFVcx7Rz0jptsYNYpmaIBszyc&state=eyJyYW5rIjoxLCJmaWx0ZXJzIjpbXX0%3D",
 *                             alt: "",
 *                             type: "IMG_VIEW"
 *                         }, {
 *                             url: "https://attribution.getkard.com/public/banners/breakfast-bunny-banner.jpg?subtype=BANNER_VIEW&offerId=629fc220b7a4290009a188ec&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWZlcnJpbmdQYXJ0bmVyVXNlcklkIjoiNDM4MTAzIiwiaXNzdWVySWQiOiIwMDAwNDMyMSIsInR5cGUiOiJPRkZFUiIsInBheWxvYWQiOnsiand0VGltZXN0YW1wIjoiMjAyNi0wNC0yMyJ9fQ.4f9QmoGpgXVIXu9Tq8XFVcx7Rz0jptsYNYpmaIBszyc&state=eyJyYW5rIjoxLCJmaWx0ZXJzIjpbXX0%3D",
 *                             alt: "",
 *                             type: "BANNER_VIEW"
 *                         }],
 *                     websiteUrl: "http://worldsgreatestchickent.test.com",
 *                     description: "Worlds Greatest Chicken brings you the tastiest crispy, double fried spicy chicken in the world."
 *                 },
 *                 relationships: {
 *                     category: {
 *                         data: [{
 *                                 type: "category",
 *                                 id: "65920081b524d126068de24a"
 *                             }, {
 *                                 type: "category",
 *                                 id: "65920081b524d126068de24c"
 *                             }]
 *                     }
 *                 }
 *             }],
 *         included: [{
 *                 type: "category",
 *                 id: "65920081b524d126068de24a",
 *                 attributes: {
 *                     name: KardApi.CategoryOption.FoodBeverage
 *                 }
 *             }, {
 *                 type: "category",
 *                 id: "65920081b524d126068de24c",
 *                 attributes: {
 *                     name: KardApi.CategoryOption.DepartmentStores
 *                 }
 *             }],
 *         links: {
 *             self: "/v2/issuers/{organizationId}/users/{userId}/offers?page[size]=1?sort=-startDate",
 *             next: "/v2/issuers/{organizationId}/users/{userId}/offers?page[after]=NDMyNzQyODI3OTQw&page[size]=1?&sort=-startDate"
 *         },
 *         meta: {
 *             availableCategories: [{
 *                     type: "category",
 *                     id: "65920081b524d126068de24a",
 *                     attributes: {
 *                         name: KardApi.CategoryOption.FoodBeverage
 *                     }
 *                 }, {
 *                     type: "category",
 *                     id: "65920081b524d126068de24c",
 *                     attributes: {
 *                         name: KardApi.CategoryOption.DepartmentStores
 *                     }
 *                 }]
 *         }
 *     }
 */
export interface OffersResponseObject {
    data: KardApi.users.OfferDataUnion[];
    links: KardApi.Links;
    included?: KardApi.users.EligibilityOfferIncluded[] | undefined;
    meta?: KardApi.users.OffersMeta | undefined;
}
