// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Metadata about the full result set across all pages
 */
export interface OffersMeta {
    /** All distinct categories available across the entire filtered result set, not just the current page */
    availableCategories?: KardApi.users.CategoryIncluded[] | undefined;
    /** Display name of the placement, resolved server-side from its id. Populated only on the Get Placement Content endpoint; absent on the Get Offers By User endpoint. */
    placementName?: string | undefined;
}
