// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Attributes of a placement batch slot.
 */
export interface PlacementBatchAttributes {
    /** Display name for the slot. Falls back to the slot's customer-defined alias, or — when the alias is absent — the name of the placement referenced by the slot. */
    name: string;
    /** Short, human-readable description of how long the slot stays activated after a user taps activate. Derived from the parent placement's `refreshInterval` (e.g. `"Activated for 24 hours"`). */
    shortDescription: string;
    /** Longer, human-readable description of the slot's activation behavior: clarifies that the offers displayed under this slot are the ones that will be activated for the user when they tap activate, and for how long they will remain active. */
    longDescription: string;
    /** Whether the slot is still considered "fresh" for the user. Set to false only when the slot's `expiresAt` is in the past AND the slot resolves to a non-empty offer set; an empty offer set keeps the slot active so partner UIs do not promote "tap to refresh" with nothing to show. */
    isActive: boolean;
    /** Timestamp of the most recent placementSlotAttribution ACTIVATE event for this (user, placement, slot). Absent for cold slots that have never been activated. */
    lastActivatedAt?: string | undefined;
    /** Computed as `lastActivatedAt + placement.refreshInterval`. Absent for cold slots that have never been activated. */
    expiresAt?: string | undefined;
    /** Slot-level UI components. Carries a `cta` (POST to the slot's activate endpoint) when the slot has no active (non-expired) activation, or a `logoFlare` decoration when it does — mutually exclusive on a single slot. */
    components?: KardApi.users.OfferComponents | undefined;
    /** Slot-level visual assets. Currently a single `IMG_VIEW` SVG showing the slot's initials, themed via the `--icon-fill` CSS custom property. */
    assets?: KardApi.users.Asset[] | undefined;
    /** The set of offers eligible for the user under this slot's content strategy. */
    offers: KardApi.users.OfferDataUnion[];
}
