// This file was auto-generated by Fern from our API Definition.

/** Supported separator styles between segment nodes */
export const ProgressBarSegmentSeparator = {
    Line: "LINE",
} as const;
export type ProgressBarSegmentSeparator =
    (typeof ProgressBarSegmentSeparator)[keyof typeof ProgressBarSegmentSeparator];
