// This file was auto-generated by Fern from our API Definition.

/**
 * Label configuration for a single node within a segment
 */
export interface ProgressBarSegmentLabel {
    /** Title text for the segment node */
    title: string;
    /** Description text for the segment node */
    description: string;
}
