// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Progress bar component for tracking offer redemption progress
 */
export interface ProgressBar {
    /** Total number of redemptions allowed */
    total: number;
    /** Number of redemptions the user has completed */
    currentProgress: number;
    /** Formatted label for the progress bar */
    label: string;
    /** Whether the progress bar should be displayed as segmented */
    segmented: boolean;
    /** Segment configuration for the progress bar in different layouts */
    segments?: KardApi.users.ProgressBarSegments;
    /** Labels to render around the progress bar in different layouts */
    labels: KardApi.users.ProgressBarLabels;
}
