// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Segment configuration for a specific layout
 */
export interface ProgressBarSegment {
    /** SVG icon to use for each segment */
    icon?: string;
    /** Position of the segment within the layout */
    position: KardApi.users.ProgressBarSegmentPosition;
}
