// This file was auto-generated by Fern from our API Definition.

/**
 * Error response indicating that the network is blocked.
 *
 * @example
 *     {
 *         message: "Unauthorized"
 *     }
 */
export interface NetworkBlockedErrorBody {
    /** A message indicating that the network is blocked. */
    message: string;
}
