// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * @example
 *     {
 *         timestamp: "2024-10-01T01:23:45Z",
 *         amount: 1000,
 *         merchantId: "6e21318c9b346f12387ffe73",
 *         merchantNetwork: "REWARDSNETWORK",
 *         offerId: "6e21318c9b346f12387ffe73",
 *         commissionToIssuer: 121,
 *         receivedCommissionInCents: 60,
 *         usersCommissionInCents: 100
 *     }
 */
export interface BillingIssuerMatchedTransaction {
    /** Transaction timestamp */
    timestamp: string;
    /** Transaction amount in cents */
    amount: number;
    /** Merchant ID */
    merchantId: string;
    /** Merchant network */
    merchantNetwork: string;
    /** The ID of the offer */
    offerId: KardApi.OfferId;
    /** Total Commission to issuer in cents */
    commissionToIssuer: number;
    /** Total Commission received by Kard in cents */
    receivedCommissionInCents: number;
    /** Total Commission received by cardholder in cents */
    usersCommissionInCents: number;
}
