// This file was auto-generated by Fern from our API Definition.

export interface EomUpdatePayload {
    /** Type of update */
    type: "matchedTransaction";
    /** matchedTransactionId */
    id: string;
    attributes: Record<string, unknown>;
}
