// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * @example
 *     {
 *         data: {
 *             "12345": {
 *                 timestamp: "2024-10-01T01:23:45Z",
 *                 amount: 1000,
 *                 merchantId: "6e21318c9b346f12387ffe73",
 *                 merchantNetwork: "REWARDSNETWORK",
 *                 offerId: "6e21318c9b346f12387ffe73",
 *                 commissionToIssuer: 121,
 *                 receivedCommissionInCents: 60,
 *                 usersCommissionInCents: 100
 *             }
 *         }
 *     }
 */
export interface GetIssuerMatchedTransactionInfoResponseObject {
    data: Record<string, KardApi.BillingIssuerMatchedTransaction>;
}
