// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

export interface CreateUploadPartResponseData {
    /** Id of the upload to add parts */
    id: string;
    attributes: KardApi.EmptyObject;
}
