// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

export type CreateUploadResponseDataUnion = KardApi.users.CreateUploadResponseDataUnion.HistoricalTransactionStart;

export namespace CreateUploadResponseDataUnion {
    export interface HistoricalTransactionStart extends KardApi.users.CreateUploadResponseData {
        type: "historicalTransactionStart";
    }
}
