// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

export type CreateUploadPartResponseDataUnion = KardApi.users.CreateUploadPartResponseDataUnion.HistoricalTransaction;

export namespace CreateUploadPartResponseDataUnion {
    export interface HistoricalTransaction extends KardApi.users.CreateUploadPartResponseData {
        type: "historicalTransaction";
    }
}
