// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

export type CreateUploadRequestDataUnion = KardApi.users.CreateUploadRequestDataUnion.HistoricalTransactionStart;

export namespace CreateUploadRequestDataUnion {
    export interface HistoricalTransactionStart extends KardApi.users.StartHistoricalUploadNoData {
        type: "historicalTransactionStart";
    }
}
