// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

export interface UpdateUploadResponseData {
    /** Upload id to reference in subsequent upload request */
    id: string;
    attributes: KardApi.EmptyObject;
}
