// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

export type UpdateUploadResponseDataUnion = KardApi.users.UpdateUploadResponseDataUnion.HistoricalTransactionComplete;

export namespace UpdateUploadResponseDataUnion {
    export interface HistoricalTransactionComplete extends KardApi.users.UpdateUploadResponseData {
        type: "historicalTransactionComplete";
    }
}
