// This file was auto-generated by Fern from our API Definition.

import * as KardApi from "../../../src/api/index";
import { KardApiClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("ChildrenClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    type: "organization",
                    id: "id",
                    attributes: { name: "name", externalId: "externalId", bins: ["bins", "bins"] },
                },
                {
                    type: "organization",
                    id: "id",
                    attributes: { name: "name", externalId: "externalId", bins: ["bins", "bins"] },
                },
            ],
            links: { self: "self", prev: "prev", next: "next" },
            meta: { pageSize: 1, hasNextPage: true },
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/children")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.children.list("organizationId");
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/children")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.list("organizationId");
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/children")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.list("organizationId");
        }).rejects.toThrow(KardApi.ForbiddenError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/children")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.list("organizationId");
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/children")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.list("organizationId");
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { data: { type: "organization", attributes: { name: "name" } } };
        const rawResponseBody = {
            type: "organization",
            id: "id",
            attributes: { name: "name", externalId: "externalId", bins: ["bins", "bins"] },
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/children")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.children.create("organizationId", {
            data: {
                type: "organization",
                attributes: {
                    name: "name",
                },
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { data: { type: "organization", attributes: { name: "name" } } };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/children")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.create("organizationId", {
                data: {
                    type: "organization",
                    attributes: {
                        name: "name",
                    },
                },
            });
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { data: { type: "organization", attributes: { name: "name" } } };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/children")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.create("organizationId", {
                data: {
                    type: "organization",
                    attributes: {
                        name: "name",
                    },
                },
            });
        }).rejects.toThrow(KardApi.ForbiddenError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { data: { type: "organization", attributes: { name: "name" } } };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/children")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.create("organizationId", {
                data: {
                    type: "organization",
                    attributes: {
                        name: "name",
                    },
                },
            });
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { data: { type: "organization", attributes: { name: "name" } } };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/children")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.create("organizationId", {
                data: {
                    type: "organization",
                    attributes: {
                        name: "name",
                    },
                },
            });
        }).rejects.toThrow(KardApi.ConflictError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { data: { type: "organization", attributes: { name: "name" } } };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/children")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.create("organizationId", {
                data: {
                    type: "organization",
                    attributes: {
                        name: "name",
                    },
                },
            });
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            type: "organization",
            id: "id",
            attributes: { name: "name", externalId: "externalId", bins: ["bins", "bins"] },
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/children/childId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.children.get("organizationId", "childId");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/children/childId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.get("organizationId", "childId");
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/children/childId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.get("organizationId", "childId");
        }).rejects.toThrow(KardApi.ForbiddenError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/children/childId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.get("organizationId", "childId");
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/children/childId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.get("organizationId", "childId");
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { data: { type: "organization", attributes: {} } };
        const rawResponseBody = {
            type: "organization",
            id: "id",
            attributes: { name: "name", externalId: "externalId", bins: ["bins", "bins"] },
        };

        server
            .mockEndpoint()
            .patch("/v2/issuers/organizationId/children/childId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.children.update("organizationId", "childId", {
            data: {
                type: "organization",
                attributes: {},
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { data: { type: "organization", attributes: {} } };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .patch("/v2/issuers/organizationId/children/childId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.update("organizationId", "childId", {
                data: {
                    type: "organization",
                    attributes: {},
                },
            });
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { data: { type: "organization", attributes: {} } };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .patch("/v2/issuers/organizationId/children/childId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.update("organizationId", "childId", {
                data: {
                    type: "organization",
                    attributes: {},
                },
            });
        }).rejects.toThrow(KardApi.ForbiddenError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { data: { type: "organization", attributes: {} } };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .patch("/v2/issuers/organizationId/children/childId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.update("organizationId", "childId", {
                data: {
                    type: "organization",
                    attributes: {},
                },
            });
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { data: { type: "organization", attributes: {} } };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .patch("/v2/issuers/organizationId/children/childId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.update("organizationId", "childId", {
                data: {
                    type: "organization",
                    attributes: {},
                },
            });
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { data: { type: "organization", attributes: {} } };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .patch("/v2/issuers/organizationId/children/childId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.update("organizationId", "childId", {
                data: {
                    type: "organization",
                    attributes: {},
                },
            });
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { data: { type: "type", id: "id", attributes: {} } };

        server
            .mockEndpoint()
            .delete("/v2/issuers/organizationId/children/childId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.children.delete("organizationId", "childId");
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .delete("/v2/issuers/organizationId/children/childId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.delete("organizationId", "childId");
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .delete("/v2/issuers/organizationId/children/childId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.delete("organizationId", "childId");
        }).rejects.toThrow(KardApi.ForbiddenError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .delete("/v2/issuers/organizationId/children/childId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.delete("organizationId", "childId");
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .delete("/v2/issuers/organizationId/children/childId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.children.delete("organizationId", "childId");
        }).rejects.toThrow(KardApi.InternalServerError);
    });
});
