// This file was auto-generated by Fern from our API Definition.

export interface FileMetadataAttribute {
    /** The name of the file. */
    fileName: string;
    /** ISO 8601 timestamp (ISO8601) when the file was originally sent/created. */
    sentAt: string;
    /** ISO 8601 timestamp (ISO8601) when the file was last modified. */
    lastModified: string;
    /** Temporary URL that provides direct access to download the file for 30 minutes. */
    downloadUrl: string;
}
