/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KardApi from "../../../index.js";

/**
 * @example
 *     {
 *         data: {
 *             type: "user",
 *             id: "1234567890",
 *             attributes: {}
 *         }
 *     }
 */
export interface DeleteUserResponseObject {
    data: KardApi.UserResponseUnionNoData;
}
