// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * @example
 *     {
 *         data: {
 *             type: "user",
 *             id: "1234567890",
 *             attributes: {
 *                 zipCode: "11238",
 *                 enrolledRewards: [KardApi.EnrolledRewardsType.Cardlinked]
 *             }
 *         }
 *     }
 */
export interface UpdateUserObject {
    data: KardApi.UserRequestDataUnion;
}
