// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export interface UpdateUserRequestAttributes {
    /** Rewards programs to enroll the user in. If an empty array is supplied, the user will not be enrolled in any programs. */
    enrolledRewards: KardApi.EnrolledRewardsType[];
    /** Zipcode of user */
    zipCode?: string | undefined;
    /** Email address of user */
    email?: string | undefined;
    /** Hashed email address of user (using SHA-256) */
    hashedEmail?: string | undefined;
    /** Phone number of user in E.164 format */
    phoneNumber?: string | undefined;
    /** Birth year of user */
    birthYear?: string | undefined;
}
