// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Attributes for creating a content strategy
 *
 * @example
 *     {
 *         name: "Featured Travel",
 *         filters: [KardApi.organizations.ContentStrategyFilter.HighestCashback, KardApi.organizations.ContentStrategyFilter.NewlyLive],
 *         categories: [KardApi.CategoryOption.Travel],
 *         categoryExclusions: [KardApi.CategoryOption.Gas],
 *         merchantExclusions: ["merchant-abc"]
 *     }
 */
export interface CreateContentStrategyAttributes {
    /** Name of the content strategy (unique within an organization) */
    name: string;
    /** Filters applied when selecting offers for the strategy */
    filters: KardApi.organizations.ContentStrategyFilter[];
    /** Merchant categories to include */
    categories: KardApi.CategoryOption[];
    /** Merchant categories to exclude */
    categoryExclusions: KardApi.CategoryOption[];
    /** Merchant IDs to exclude */
    merchantExclusions: string[];
}
