// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Request body for creating a content strategy
 *
 * @example
 *     {
 *         data: {
 *             type: "contentStrategy",
 *             attributes: {
 *                 name: "Featured Travel",
 *                 filter: KardApi.organizations.ContentStrategyFilter.HighestCashback,
 *                 categories: [KardApi.CategoryOption.Travel],
 *                 categoryExclusions: [KardApi.CategoryOption.Gas],
 *                 merchantExclusions: ["merchant-abc"]
 *             }
 *         }
 *     }
 */
export interface CreateContentStrategyRequestBody {
    /** Content strategy data for creation */
    data: KardApi.organizations.CreateContentStrategyRequestData;
}
