// This file was auto-generated by Fern from our API Definition.

/** Offer feature applied to the offers selected by a content strategy. A strategy may have any number of offer features. */
export const OfferFeatures = {
    Interactive: "INTERACTIVE",
} as const;
export type OfferFeatures = (typeof OfferFeatures)[keyof typeof OfferFeatures];
