// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../index.js";

/**
 * Content strategy data structure for update
 */
export interface UpdateContentStrategyRequestData {
    /** Resource type identifier */
    type: "contentStrategy";
    /** Content strategy attributes for update */
    attributes: KardApi.organizations.UpdateContentStrategyAttributes;
}
