// This file was auto-generated by Fern from our API Definition.

/** Rewards programs an organization is enrolled in */
export const EnrolledReward = {
    Cardlinked: "CARDLINKED",
    Affiliate: "AFFILIATE",
} as const;
export type EnrolledReward = (typeof EnrolledReward)[keyof typeof EnrolledReward];
