// This file was auto-generated by Fern from our API Definition.

/** Card networks supported by an organization. Deliberately not commons.CardNetwork: that type spells Amex `AMERICANEXPRESS`, which the organizations database rejects. The organizations.card_networks CHECK constraint permits `AMERICAN_EXPRESS` (canonical, and what this service writes) and `AMERICAN EXPRESS` (legacy, present in existing rows only). The name differs from commons.CardNetwork because a type may not shadow one from an imported file. */
export const OrganizationCardNetwork = {
    Visa: "VISA",
    Mastercard: "MASTERCARD",
    AmericanExpress: "AMERICAN_EXPRESS",
    Discover: "DISCOVER",
} as const;
export type OrganizationCardNetwork = (typeof OrganizationCardNetwork)[keyof typeof OrganizationCardNetwork];
