// This file was auto-generated by Fern from our API Definition.

import * as KardApi from "../../../src/api/index";
import { KardApiClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("AttributionsClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            data: [
                {
                    type: "offerAttribution",
                    attributes: {
                        entityId: "60e4ba1da31c5a22a144c075",
                        eventCode: "VIEW",
                        medium: "SEARCH",
                        eventDate: "2025-01-01T00:00:00Z",
                    },
                },
                {
                    type: "offerAttribution",
                    attributes: {
                        entityId: "60e4ba1da31c5a22a144c077",
                        eventCode: "IMPRESSION",
                        medium: "EMAIL",
                        eventDate: "2025-01-01T00:00:00Z",
                    },
                },
                {
                    type: "notificationAttribution",
                    attributes: {
                        entityId: "60e4ba1da31c5a22a144c076",
                        eventCode: "IMPRESSION",
                        medium: "PUSH",
                        eventDate: "2025-01-01T00:00:00Z",
                    },
                },
            ],
        };
        const rawResponseBody = {
            data: {
                type: "job",
                id: "c94a93a7-beb9-4e58-960c-2c812f849398",
                attributes: { status: "queued", message: "Attribution events are queued for processing" },
            },
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organization-123/users/user-123/attributions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.attributions.create("organization-123", "user-123", {
            data: [
                {
                    type: "offerAttribution",
                    attributes: {
                        entityId: "60e4ba1da31c5a22a144c075",
                        eventCode: "VIEW",
                        medium: "SEARCH",
                        eventDate: "2025-01-01T00:00:00Z",
                    },
                },
                {
                    type: "offerAttribution",
                    attributes: {
                        entityId: "60e4ba1da31c5a22a144c077",
                        eventCode: "IMPRESSION",
                        medium: "EMAIL",
                        eventDate: "2025-01-01T00:00:00Z",
                    },
                },
                {
                    type: "notificationAttribution",
                    attributes: {
                        entityId: "60e4ba1da31c5a22a144c076",
                        eventCode: "IMPRESSION",
                        medium: "PUSH",
                        eventDate: "2025-01-01T00:00:00Z",
                    },
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            data: [
                {
                    type: "offerAttribution",
                    attributes: {
                        entityId: "entityId",
                        eventCode: "IMPRESSION",
                        medium: "BROWSE",
                        eventDate: "2024-01-15T09:30:00Z",
                    },
                },
                {
                    type: "offerAttribution",
                    attributes: {
                        entityId: "entityId",
                        eventCode: "IMPRESSION",
                        medium: "BROWSE",
                        eventDate: "2024-01-15T09:30:00Z",
                    },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/attributions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.attributions.create("organizationId", "userId", {
                data: [
                    {
                        type: "offerAttribution",
                        attributes: {
                            entityId: "entityId",
                            eventCode: "IMPRESSION",
                            medium: "BROWSE",
                            eventDate: "2024-01-15T09:30:00Z",
                        },
                    },
                    {
                        type: "offerAttribution",
                        attributes: {
                            entityId: "entityId",
                            eventCode: "IMPRESSION",
                            medium: "BROWSE",
                            eventDate: "2024-01-15T09:30:00Z",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            data: [
                {
                    type: "offerAttribution",
                    attributes: {
                        entityId: "entityId",
                        eventCode: "IMPRESSION",
                        medium: "BROWSE",
                        eventDate: "2024-01-15T09:30:00Z",
                    },
                },
                {
                    type: "offerAttribution",
                    attributes: {
                        entityId: "entityId",
                        eventCode: "IMPRESSION",
                        medium: "BROWSE",
                        eventDate: "2024-01-15T09:30:00Z",
                    },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/attributions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.attributions.create("organizationId", "userId", {
                data: [
                    {
                        type: "offerAttribution",
                        attributes: {
                            entityId: "entityId",
                            eventCode: "IMPRESSION",
                            medium: "BROWSE",
                            eventDate: "2024-01-15T09:30:00Z",
                        },
                    },
                    {
                        type: "offerAttribution",
                        attributes: {
                            entityId: "entityId",
                            eventCode: "IMPRESSION",
                            medium: "BROWSE",
                            eventDate: "2024-01-15T09:30:00Z",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            data: [
                {
                    type: "offerAttribution",
                    attributes: {
                        entityId: "entityId",
                        eventCode: "IMPRESSION",
                        medium: "BROWSE",
                        eventDate: "2024-01-15T09:30:00Z",
                    },
                },
                {
                    type: "offerAttribution",
                    attributes: {
                        entityId: "entityId",
                        eventCode: "IMPRESSION",
                        medium: "BROWSE",
                        eventDate: "2024-01-15T09:30:00Z",
                    },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/attributions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.attributions.create("organizationId", "userId", {
                data: [
                    {
                        type: "offerAttribution",
                        attributes: {
                            entityId: "entityId",
                            eventCode: "IMPRESSION",
                            medium: "BROWSE",
                            eventDate: "2024-01-15T09:30:00Z",
                        },
                    },
                    {
                        type: "offerAttribution",
                        attributes: {
                            entityId: "entityId",
                            eventCode: "IMPRESSION",
                            medium: "BROWSE",
                            eventDate: "2024-01-15T09:30:00Z",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("activate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                type: "offerAttribution",
                id: "c94a93a7-beb9-4e58-960c-2c812f849398",
                attributes: {
                    entityId: "offer-456",
                    eventCode: "ACTIVATE",
                    medium: "CTA",
                    eventDate: "2025-01-01T00:00:00Z",
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organization-123/users/user-123/offers/offer-456/activate")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.attributions.activate("organization-123", "user-123", "offer-456");
        expect(response).toEqual(rawResponseBody);
    });

    test("activate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/offers/offerId/activate")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.attributions.activate("organizationId", "userId", "offerId");
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("activate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/offers/offerId/activate")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.attributions.activate("organizationId", "userId", "offerId");
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("activate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/offers/offerId/activate")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.attributions.activate("organizationId", "userId", "offerId");
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("boost (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                type: "offerAttribution",
                id: "c94a93a7-beb9-4e58-960c-2c812f849398",
                attributes: {
                    entityId: "offer-456",
                    eventCode: "BOOST",
                    medium: "CTA",
                    eventDate: "2025-01-01T00:00:00Z",
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organization-123/users/user-123/offers/offer-456/boost")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.attributions.boost("organization-123", "user-123", "offer-456");
        expect(response).toEqual(rawResponseBody);
    });

    test("boost (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/offers/offerId/boost")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.attributions.boost("organizationId", "userId", "offerId");
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("boost (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/offers/offerId/boost")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.attributions.boost("organizationId", "userId", "offerId");
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("boost (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/offers/offerId/boost")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.attributions.boost("organizationId", "userId", "offerId");
        }).rejects.toThrow(KardApi.InvalidRequest);
    });
});
