// This file was auto-generated by Fern from our API Definition.

import * as KardApi from "../../../src/api/index";
import { KardApiClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("AuthClient", () => {
    test("getWebViewToken (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
            expires_in: 3600,
            token_type: "Bearer",
        };

        server
            .mockEndpoint()
            .post("/v2/auth/issuers/organization-123/users/user-123/token")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.auth.getWebViewToken("organization-123", "user-123");
        expect(response).toEqual(rawResponseBody);
    });

    test("getWebViewToken (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/auth/issuers/organizationId/users/userId/token")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.auth.getWebViewToken("organizationId", "userId");
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("getWebViewToken (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .post("/v2/auth/issuers/organizationId/users/userId/token")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.auth.getWebViewToken("organizationId", "userId");
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });
});
