// This file was auto-generated by Fern from our API Definition.

import * as KardApi from "../../../src/api/index";
import { KardApiClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("RewardsClient", () => {
    test("offers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    type: "standardOffer",
                    id: "5e27318c9b346f00087fbb5c",
                    attributes: {
                        name: "Worlds Greatest Chicken",
                        terms: "Worlds Greatest Chicken offers are only available within US Locations.",
                        purchaseChannel: ["INSTORE"],
                        userReward: { type: "PERCENT", value: 5.7 },
                        startDate: "2024-11-17T05:00:00Z",
                        expirationDate: "2025-03-17T05:00:00Z",
                        minRewardAmount: { type: "CENTS", value: 500 },
                        maxRewardAmount: { type: "CENTS", value: 2000 },
                        minTransactionAmount: { type: "CENTS", value: 500 },
                        maxTransactionAmount: { type: "CENTS", value: 10000 },
                        maxRedemptions: 1,
                        isTargeted: true,
                        assets: [
                            {
                                type: "IMG_VIEW",
                                url: "http://assets.getkard.com/logo/img?attribution-tokens",
                                alt: "Worlds Greatest Chicken Logo Image",
                            },
                            {
                                type: "BANNER_VIEW",
                                url: "http://assets.getkard.com/banner/img?attribution-tokens",
                                alt: "Worlds Greatest Chicken Banner Image",
                            },
                        ],
                        websiteUrl: "http://worldsgreatestchickent.test.com",
                        description:
                            "Worlds Greatest Chicken brings you the tastiest crispy, double fried spicy chicken in the world.",
                    },
                    relationships: {
                        category: {
                            data: [
                                { type: "category", id: "65920081b524d126068de24a" },
                                { type: "category", id: "65920081b524d126068de24c" },
                            ],
                        },
                    },
                },
            ],
            included: [
                { type: "category", id: "65920081b524d126068de24a", attributes: { name: "Food & Beverage" } },
                { type: "category", id: "65920081b524d126068de24c", attributes: { name: "Department Stores" } },
            ],
            links: {
                self: "/v2/issuers/{organizationId}/users/{userId}/offers?page[size]=1?sort=-startDate",
                next: "/v2/issuers/{organizationId}/users/{userId}/offers?page[after]=NDMyNzQyODI3OTQw&page[size]=1?&sort=-startDate",
            },
            meta: {
                availableCategories: [
                    { type: "category", id: "65920081b524d126068de24a", attributes: { name: "Food & Beverage" } },
                    { type: "category", id: "65920081b524d126068de24c", attributes: { name: "Department Stores" } },
                ],
            },
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organization-123/users/user-123/offers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.rewards.offers("organization-123", "user-123", {
            "page[size]": 1,
            "filter[isTargeted]": true,
            sort: "-startDate",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("offers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/offers")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.rewards.offers("organizationId", "userId");
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("offers (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/offers")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.rewards.offers("organizationId", "userId");
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("offers (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/offers")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.rewards.offers("organizationId", "userId");
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("offers (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/offers")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.rewards.offers("organizationId", "userId");
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("placementOffers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    type: "standardOffer",
                    relationships: {
                        category: {
                            data: [
                                { id: "id", type: "category" },
                                { id: "id", type: "category" },
                            ],
                        },
                    },
                    id: "id",
                    attributes: {
                        terms: "terms",
                        maxRedemptions: 1,
                        name: "name",
                        purchaseChannel: ["INSTORE", "INSTORE"],
                        userReward: { type: "FLAT", value: 1.1 },
                        assets: [
                            { type: "type", url: "url", alt: "alt" },
                            { type: "type", url: "url", alt: "alt" },
                        ],
                        startDate: "2024-01-15T09:30:00Z",
                        expirationDate: "2024-01-15T09:30:00Z",
                        isTargeted: true,
                        minTransactionAmount: { type: "CENTS", value: 1 },
                        maxTransactionAmount: { type: "CENTS", value: 1 },
                        minRewardAmount: { type: "CENTS", value: 1 },
                        maxRewardAmount: { type: "CENTS", value: 1 },
                        websiteUrl: "websiteUrl",
                        description: "description",
                        components: {
                            shortDescription: "shortDescription",
                            longDescription: "longDescription",
                            baseReward: "baseReward",
                            boostedReward: "boostedReward",
                            cta: {
                                buttonText: "buttonText",
                                buttonStyle: "PRIMARY",
                                action: { url: "url", method: "method" },
                                startIcon: "startIcon",
                            },
                            tags: ["tags", "tags"],
                            detailTags: ["detailTags", "detailTags"],
                            logoFlare: { borderColor: "PRIMARY", badge: { icon: "icon", position: "TOP_RIGHT" } },
                            progressBar: {
                                total: 1,
                                currentProgress: 1,
                                label: "label",
                                segmented: true,
                                labels: { details: {}, default: {} },
                            },
                        },
                    },
                },
                {
                    type: "standardOffer",
                    relationships: {
                        category: {
                            data: [
                                { id: "id", type: "category" },
                                { id: "id", type: "category" },
                            ],
                        },
                    },
                    id: "id",
                    attributes: {
                        terms: "terms",
                        maxRedemptions: 1,
                        name: "name",
                        purchaseChannel: ["INSTORE", "INSTORE"],
                        userReward: { type: "FLAT", value: 1.1 },
                        assets: [
                            { type: "type", url: "url", alt: "alt" },
                            { type: "type", url: "url", alt: "alt" },
                        ],
                        startDate: "2024-01-15T09:30:00Z",
                        expirationDate: "2024-01-15T09:30:00Z",
                        isTargeted: true,
                        minTransactionAmount: { type: "CENTS", value: 1 },
                        maxTransactionAmount: { type: "CENTS", value: 1 },
                        minRewardAmount: { type: "CENTS", value: 1 },
                        maxRewardAmount: { type: "CENTS", value: 1 },
                        websiteUrl: "websiteUrl",
                        description: "description",
                        components: {
                            shortDescription: "shortDescription",
                            longDescription: "longDescription",
                            baseReward: "baseReward",
                            boostedReward: "boostedReward",
                            cta: {
                                buttonText: "buttonText",
                                buttonStyle: "PRIMARY",
                                action: { url: "url", method: "method" },
                                startIcon: "startIcon",
                            },
                            tags: ["tags", "tags"],
                            detailTags: ["detailTags", "detailTags"],
                            logoFlare: { borderColor: "PRIMARY", badge: { icon: "icon", position: "TOP_RIGHT" } },
                            progressBar: {
                                total: 1,
                                currentProgress: 1,
                                label: "label",
                                segmented: true,
                                labels: { details: {}, default: {} },
                            },
                        },
                    },
                },
            ],
            links: { self: "self", prev: "prev", next: "next" },
            included: [
                { attributes: { name: "Arts & Entertainment" }, id: "id", type: "category" },
                { attributes: { name: "Arts & Entertainment" }, id: "id", type: "category" },
            ],
            meta: {
                availableCategories: [
                    { attributes: { name: "Arts & Entertainment" }, id: "id", type: "category" },
                    { attributes: { name: "Arts & Entertainment" }, id: "id", type: "category" },
                ],
            },
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/placements/placementId/offers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.rewards.placementOffers("organizationId", "userId", "placementId");
        expect(response).toEqual(rawResponseBody);
    });

    test("placementOffers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/placements/placementId/offers")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.rewards.placementOffers("organizationId", "userId", "placementId");
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("placementOffers (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/placements/placementId/offers")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.rewards.placementOffers("organizationId", "userId", "placementId");
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("placementOffers (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/placements/placementId/offers")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.rewards.placementOffers("organizationId", "userId", "placementId");
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("placementOffers (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/placements/placementId/offers")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.rewards.placementOffers("organizationId", "userId", "placementId");
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("locations (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    type: "location",
                    id: "5e27318c9b346f00087fba8l",
                    attributes: {
                        name: "Worlds Greatest Chicken",
                        address: { street: "120 Main St", city: "Philadelphia", state: "PA", zipCode: "19147" },
                        coordinates: { longitude: -75.1446869, latitude: 39.9419429 },
                        phone: "+1 (123) 555-8880",
                        operationHours: {
                            periods: [
                                { close: { day: 1, time: "1700" }, open: { day: 1, time: "0900" } },
                                { close: { day: 2, time: "1700" }, open: { day: 2, time: "0900" } },
                                { close: { day: 3, time: "1700" }, open: { day: 3, time: "0900" } },
                                { close: { day: 4, time: "1700" }, open: { day: 4, time: "0900" } },
                                { close: { day: 5, time: "1700" }, open: { day: 5, time: "0900" } },
                            ],
                            weekdayText: [
                                "Monday: 9:00 AM – 5:00 PM",
                                "Tuesday: 9:00 AM – 5:00 PM",
                                "Wednesday: 9:00 AM – 5:00 PM",
                                "Thursday: 9:00 AM – 5:00 PM",
                                "Friday: 9:00 AM – 5:00 PM",
                                "Saturday: Closed",
                                "Sunday: Closed",
                            ],
                        },
                    },
                    relationships: {
                        offers: { data: [{ type: "standardOffer", id: "5e27318c9b346f00087fbb5b" }] },
                        category: { data: [{ type: "category", id: "65920081b524d126068de24a" }] },
                    },
                },
            ],
            included: [
                { type: "category", id: "65920081b524d126068de24a", attributes: { name: "Food & Beverage" } },
                {
                    type: "standardOffer",
                    id: "5e27318c9b346f00087fbb5c",
                    attributes: {
                        name: "Worlds Greatest Chicken",
                        terms: "Worlds Greatest Chicken offers are only available within US Locations.",
                        purchaseChannel: ["INSTORE"],
                        userReward: { type: "PERCENT", value: 5.7 },
                        startDate: "2022-01-01T05:00:00Z",
                        expirationDate: "2022-01-01T05:00:00Z",
                        minRewardAmount: { type: "CENTS", value: 500 },
                        maxRewardAmount: { type: "CENTS", value: 2000 },
                        minTransactionAmount: { type: "CENTS", value: 500 },
                        maxTransactionAmount: { type: "CENTS", value: 2000 },
                        maxRedemptions: 1,
                        isTargeted: true,
                        assets: [
                            {
                                type: "IMG_VIEW",
                                url: "http://assets.getkard.com/logo/img?attribution-tokens",
                                alt: "Worlds Greatest Chicken Logo Image",
                            },
                            {
                                type: "BANNER_VIEW",
                                url: "http://assets.getkard.com/banner/img?attribution-tokens",
                                alt: "Worlds Greatest Chicken Banner Image",
                            },
                        ],
                        websiteUrl: "http://worldsgreatestchickent.test.com",
                        description:
                            "Worlds Greatest Chicken brings you the tastiest crispy, double fried spicy chicken in the world.",
                    },
                },
            ],
            links: {
                self: "/v2/issuers/{organizationId}/users/{userId}/locations?page[size]=1&filter[latitude]=39.9419429&filter[longitude]=-75.1446869&filter[radius]=10&include=offers,categories",
                next: "/v2/issuers/{organizationId}/users/{userId}/locations?page[after]=NDMyNzQyODI3OTQw&page[size]=1&filter[latitude]=39.9419429&filter[longitude]=-75.1446869&filter[radius]=10&include=offers,categories",
            },
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organization-123/users/user-123/locations")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.rewards.locations("organization-123", "user-123", {
            "page[size]": 1,
            "filter[latitude]": 39.9419429,
            "filter[longitude]": -75.1446869,
            "filter[radius]": 10,
            include: "offers,categories",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("locations (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/locations")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.rewards.locations("organizationId", "userId");
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("locations (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/locations")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.rewards.locations("organizationId", "userId");
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("locations (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/locations")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.rewards.locations("organizationId", "userId");
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("locations (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/locations")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.rewards.locations("organizationId", "userId");
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });
});
