// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entries: true
 *     }
 */
export interface GetRewardRequest {
    /** Include reward entries in the response */
    entries?: boolean;
}
