// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * Reward filtering query parameters
 */
export interface RewardsFilterOptions {
    rewardId?: KardApi.RewardId;
    transactionId?: KardApi.TransactionId;
    merchantId?: KardApi.MerchantId;
    issuerId?: KardApi.IssuerId;
    /** RFC3339 time when the reward was created */
    createdDateStart?: string;
    /** RFC3339 time when the reward was created */
    createdDateEnd?: string;
}
