// This file was auto-generated by Fern from our API Definition.

export const RewardType = {
    Matched: "MATCHED",
    Adjustment: "ADJUSTMENT",
    Reverted: "REVERTED",
} as const;
export type RewardType = (typeof RewardType)[keyof typeof RewardType];
