// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetOffersRequest {
    /** Represents a cursor value, and if provided, returns the next page of results */
    "page[after]"?: string;
    /** Represents a cursor value, and if provided, returns the previous page of results */
    "page[before]"?: string;
    /** Maximum number of records to be returned [1 - 200], (default = 200) */
    "page[size]"?: number;
    /** Comma-separated list of related resources to include (e.g., merchant,locations,segments,audiences) */
    include?: string;
    /** Filter by offer name */
    "filter[name]"?: string;
    "filter[offerType]"?: KardApi.LocationType;
    /** Filter by merchant ID */
    "filter[merchantId]"?: string;
    /** Filter by start date (ISO 8601 format) */
    "filter[startDate]"?: string;
    /** Filter by expiration date (ISO 8601 format) */
    "filter[expirationDate]"?: string;
    "filter[source]"?: KardApi.Source;
    /** Filter by offer category */
    "filter[category]"?: string;
    /** Filter by offer status */
    "filter[status]"?: KardApi.Status;
    /** Filter by id */
    "filter[id]"?: string;
    /** Filter by isTargeted */
    "filter[isTargeted]"?: boolean;
}
