// This file was auto-generated by Fern from our API Definition.

import { KardApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AuthClient", () => {
    test("getToken", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { client_id: "client_id", client_secret: "client_secret" };
        const rawResponseBody = { access_token: "access_token", expires_in: 1, token_type: "token_type" };

        server
            .mockEndpoint()
            .post("/v2/auth/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.auth.getToken({
            client_id: "client_id",
            client_secret: "client_secret",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
