// This file was auto-generated by Fern from our API Definition.

import * as KardApi from "../../src/api/index";
import { KardApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BillingServiceClient", () => {
    test("createReward (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            transactionIds: ["5e27318c9b346f00087fbb32"],
            issuerId: "5e27318c9b346f00087fbb32",
            userId: "5e27318c9b346f00087fbb32",
            description: "Reward payout for transaction",
        };
        const rawResponseBody = {
            data: {
                rewardId: "abd6e578-d130-44e6-bf4b-8dddb31038b0",
                transactionIds: ["5e27318c9b346f00087fbb32"],
                issuerId: "6e21318c9b346f12387ffe73",
                merchantId: "6e21318c9b346f12387ffe73",
                offerId: "6e21318c9b346f12387ffe73",
                userId: "6e21318c9b346f12387ffe73",
                transactionAmount: 3000,
                transactionTimestamp: "2024-10-01T01:23:45.67Z",
                issuerAmount: 100,
                cardHolderAmount: 400,
                kardFees: 50,
                createdDate: "2024-10-01T00:00:00Z",
                lastModified: "2024-10-02T00:00:00Z",
                entries: [
                    {
                        issuerAmount: 150,
                        cardHolderAmount: 500,
                        kardFees: 50,
                        description: "Reward payout for transaction",
                        type: "MATCHED",
                        createdAt: "2024-10-01T00:00:00Z",
                    },
                    {
                        issuerAmount: -50,
                        cardHolderAmount: -100,
                        kardFees: 0,
                        description: "Value adjusted upon request of issuer",
                        type: "ADJUSTMENT",
                        createdAt: "2024-10-02T00:00:00Z",
                    },
                ],
            },
        };
        server
            .mockEndpoint()
            .post("/v2/billing/rewards")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billingService.createReward({
            transactionIds: ["5e27318c9b346f00087fbb32"],
            issuerId: "5e27318c9b346f00087fbb32",
            userId: "5e27318c9b346f00087fbb32",
            description: "Reward payout for transaction",
        });
        expect(response).toEqual({
            data: {
                rewardId: "abd6e578-d130-44e6-bf4b-8dddb31038b0",
                transactionIds: ["5e27318c9b346f00087fbb32"],
                issuerId: "6e21318c9b346f12387ffe73",
                merchantId: "6e21318c9b346f12387ffe73",
                offerId: "6e21318c9b346f12387ffe73",
                userId: "6e21318c9b346f12387ffe73",
                transactionAmount: 3000,
                transactionTimestamp: "2024-10-01T01:23:45.67Z",
                issuerAmount: 100,
                cardHolderAmount: 400,
                kardFees: 50,
                createdDate: "2024-10-01T00:00:00Z",
                lastModified: "2024-10-02T00:00:00Z",
                entries: [
                    {
                        issuerAmount: 150,
                        cardHolderAmount: 500,
                        kardFees: 50,
                        description: "Reward payout for transaction",
                        type: "MATCHED",
                        createdAt: "2024-10-01T00:00:00Z",
                    },
                    {
                        issuerAmount: -50,
                        cardHolderAmount: -100,
                        kardFees: 0,
                        description: "Value adjusted upon request of issuer",
                        type: "ADJUSTMENT",
                        createdAt: "2024-10-02T00:00:00Z",
                    },
                ],
            },
        });
    });

    test("createReward (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            transactionIds: ["transactionIds", "transactionIds"],
            issuerId: "issuerId",
            userId: "userId",
            description: "description",
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/billing/rewards")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.createReward({
                transactionIds: ["transactionIds", "transactionIds"],
                issuerId: "issuerId",
                userId: "userId",
                description: "description",
            });
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("createReward (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            transactionIds: ["transactionIds", "transactionIds"],
            issuerId: "issuerId",
            userId: "userId",
            description: "description",
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/billing/rewards")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.createReward({
                transactionIds: ["transactionIds", "transactionIds"],
                issuerId: "issuerId",
                userId: "userId",
                description: "description",
            });
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("createReward (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            transactionIds: ["transactionIds", "transactionIds"],
            issuerId: "issuerId",
            userId: "userId",
            description: "description",
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/billing/rewards")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.createReward({
                transactionIds: ["transactionIds", "transactionIds"],
                issuerId: "issuerId",
                userId: "userId",
                description: "description",
            });
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("getReward (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                rewardId: "abd6e578-d130-44e6-bf4b-8dddb31038b0",
                transactionIds: ["5e27318c9b346f00087fbb32"],
                issuerId: "6e21318c9b346f12387ffe73",
                merchantId: "6e21318c9b346f12387ffe73",
                offerId: "6e21318c9b346f12387ffe73",
                userId: "6e21318c9b346f12387ffe73",
                transactionAmount: 3000,
                transactionTimestamp: "2024-10-01T01:23:45.67Z",
                issuerAmount: 100,
                cardHolderAmount: 400,
                kardFees: 50,
                createdDate: "2024-10-01T00:00:00Z",
                lastModified: "2024-10-02T00:00:00Z",
                entries: [
                    {
                        issuerAmount: 150,
                        cardHolderAmount: 500,
                        kardFees: 50,
                        description: "Reward payout for transaction",
                        type: "MATCHED",
                        createdAt: "2024-10-01T00:00:00Z",
                    },
                    {
                        issuerAmount: -50,
                        cardHolderAmount: -100,
                        kardFees: 0,
                        description: "Value adjusted upon request of issuer",
                        type: "ADJUSTMENT",
                        createdAt: "2024-10-02T00:00:00Z",
                    },
                ],
            },
        };
        server
            .mockEndpoint()
            .get("/v2/billing/rewards/abd6e578-d130-44e6-bf4b-8dddb31038b0")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billingService.getReward("abd6e578-d130-44e6-bf4b-8dddb31038b0", {
            entries: true,
        });
        expect(response).toEqual({
            data: {
                rewardId: "abd6e578-d130-44e6-bf4b-8dddb31038b0",
                transactionIds: ["5e27318c9b346f00087fbb32"],
                issuerId: "6e21318c9b346f12387ffe73",
                merchantId: "6e21318c9b346f12387ffe73",
                offerId: "6e21318c9b346f12387ffe73",
                userId: "6e21318c9b346f12387ffe73",
                transactionAmount: 3000,
                transactionTimestamp: "2024-10-01T01:23:45.67Z",
                issuerAmount: 100,
                cardHolderAmount: 400,
                kardFees: 50,
                createdDate: "2024-10-01T00:00:00Z",
                lastModified: "2024-10-02T00:00:00Z",
                entries: [
                    {
                        issuerAmount: 150,
                        cardHolderAmount: 500,
                        kardFees: 50,
                        description: "Reward payout for transaction",
                        type: "MATCHED",
                        createdAt: "2024-10-01T00:00:00Z",
                    },
                    {
                        issuerAmount: -50,
                        cardHolderAmount: -100,
                        kardFees: 0,
                        description: "Value adjusted upon request of issuer",
                        type: "ADJUSTMENT",
                        createdAt: "2024-10-02T00:00:00Z",
                    },
                ],
            },
        });
    });

    test("getReward (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/billing/rewards/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.getReward("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32");
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("getReward (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/billing/rewards/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.getReward("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32");
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("getReward (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/billing/rewards/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.getReward("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32");
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("getRewards (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    rewardId: "abd6e578-d130-44e6-bf4b-8dddb31038b0",
                    transactionIds: ["5e27318c9b346f00087fbb32"],
                    issuerId: "6e21318c9b346f12387ffe73",
                    merchantId: "6e21318c9b346f12387ffe73",
                    offerId: "6e21318c9b346f12387ffe73",
                    userId: "6e21318c9b346f12387ffe73",
                    transactionAmount: 3000,
                    transactionTimestamp: "2024-10-01T01:23:45.67Z",
                    issuerAmount: 100,
                    cardHolderAmount: 400,
                    kardFees: 50,
                    createdDate: "2024-10-01T00:00:00Z",
                    lastModified: "2024-10-02T00:00:00Z",
                    entries: [
                        {
                            issuerAmount: 150,
                            cardHolderAmount: 500,
                            kardFees: 50,
                            description: "Reward payout for transaction",
                            type: "MATCHED",
                            createdAt: "2024-10-01T00:00:00Z",
                        },
                        {
                            issuerAmount: -50,
                            cardHolderAmount: -100,
                            kardFees: 0,
                            description: "Value adjusted upon request of issuer",
                            type: "ADJUSTMENT",
                            createdAt: "2024-10-02T00:00:00Z",
                        },
                    ],
                },
            ],
            links: {
                self: "/billing/rewards?page[size]=50",
                next: "/billing/rewards?page[after]=NDMyNzQyODI3OTQw&page[size]=50",
            },
        };
        server
            .mockEndpoint()
            .get("/v2/billing/rewards")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billingService.getRewards();
        expect(response).toEqual({
            data: [
                {
                    rewardId: "abd6e578-d130-44e6-bf4b-8dddb31038b0",
                    transactionIds: ["5e27318c9b346f00087fbb32"],
                    issuerId: "6e21318c9b346f12387ffe73",
                    merchantId: "6e21318c9b346f12387ffe73",
                    offerId: "6e21318c9b346f12387ffe73",
                    userId: "6e21318c9b346f12387ffe73",
                    transactionAmount: 3000,
                    transactionTimestamp: "2024-10-01T01:23:45.67Z",
                    issuerAmount: 100,
                    cardHolderAmount: 400,
                    kardFees: 50,
                    createdDate: "2024-10-01T00:00:00Z",
                    lastModified: "2024-10-02T00:00:00Z",
                    entries: [
                        {
                            issuerAmount: 150,
                            cardHolderAmount: 500,
                            kardFees: 50,
                            description: "Reward payout for transaction",
                            type: "MATCHED",
                            createdAt: "2024-10-01T00:00:00Z",
                        },
                        {
                            issuerAmount: -50,
                            cardHolderAmount: -100,
                            kardFees: 0,
                            description: "Value adjusted upon request of issuer",
                            type: "ADJUSTMENT",
                            createdAt: "2024-10-02T00:00:00Z",
                        },
                    ],
                },
            ],
            links: {
                self: "/billing/rewards?page[size]=50",
                next: "/billing/rewards?page[after]=NDMyNzQyODI3OTQw&page[size]=50",
            },
        });
    });

    test("getRewards (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/billing/rewards")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.getRewards();
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("getRewards (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/billing/rewards")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.getRewards();
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("getRewards (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/billing/rewards")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.getRewards();
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("getRewardEntries (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    rewardId: "abd6e578-d130-44e6-bf4b-8dddb31038b0",
                    transactionIds: ["5e27318c9b346f00087fbb32"],
                    transactionAmount: 3000,
                    transactionTimestamp: "2024-10-01T01:23:45Z",
                    offerId: "6e21318c9b346f12387ffe73",
                    issuerId: "6e21318c9b346f12387ffe73",
                    userId: "6e21318c9b346f12387ffe73",
                    merchantId: "6e21318c9b346f12387ffe73",
                    issuerAmount: 150,
                    cardHolderAmount: 500,
                    kardFees: 50,
                    description: "Reward payout for transaction",
                    type: "MATCHED",
                    createdAt: "2024-10-01T00:00:00Z",
                },
            ],
            links: {
                self: "/billing/rewards/entries?page[size]=50",
                next: "/billing/rewards/entries?page[after]=NDMyNzQyODI3OTQw&page[size]=50",
            },
        };
        server
            .mockEndpoint()
            .get("/v2/billing/rewards/entries")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billingService.getRewardEntries();
        expect(response).toEqual({
            data: [
                {
                    rewardId: "abd6e578-d130-44e6-bf4b-8dddb31038b0",
                    transactionIds: ["5e27318c9b346f00087fbb32"],
                    transactionAmount: 3000,
                    transactionTimestamp: "2024-10-01T01:23:45Z",
                    offerId: "6e21318c9b346f12387ffe73",
                    issuerId: "6e21318c9b346f12387ffe73",
                    userId: "6e21318c9b346f12387ffe73",
                    merchantId: "6e21318c9b346f12387ffe73",
                    issuerAmount: 150,
                    cardHolderAmount: 500,
                    kardFees: 50,
                    description: "Reward payout for transaction",
                    type: "MATCHED",
                    createdAt: "2024-10-01T00:00:00Z",
                },
            ],
            links: {
                self: "/billing/rewards/entries?page[size]=50",
                next: "/billing/rewards/entries?page[after]=NDMyNzQyODI3OTQw&page[size]=50",
            },
        });
    });

    test("getRewardEntries (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/billing/rewards/entries")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.getRewardEntries();
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("getRewardEntries (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/billing/rewards/entries")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.getRewardEntries();
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("getRewardEntries (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/billing/rewards/entries")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.getRewardEntries();
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("updateReward (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            issuerAmount: 0,
            cardHolderAmount: 0,
            kardFees: -50,
            description: "Waive fees for transaction",
        };
        const rawResponseBody = {
            data: {
                rewardId: "abd6e578-d130-44e6-bf4b-8dddb31038b0",
                transactionIds: ["5e27318c9b346f00087fbb32"],
                issuerId: "6e21318c9b346f12387ffe73",
                merchantId: "6e21318c9b346f12387ffe73",
                offerId: "6e21318c9b346f12387ffe73",
                userId: "6e21318c9b346f12387ffe73",
                transactionAmount: 3000,
                transactionTimestamp: "2024-10-01T01:23:45.67Z",
                issuerAmount: 100,
                cardHolderAmount: 400,
                kardFees: 50,
                createdDate: "2024-10-01T00:00:00Z",
                lastModified: "2024-10-02T00:00:00Z",
                entries: [
                    {
                        issuerAmount: 150,
                        cardHolderAmount: 500,
                        kardFees: 50,
                        description: "Reward payout for transaction",
                        type: "MATCHED",
                        createdAt: "2024-10-01T00:00:00Z",
                    },
                    {
                        issuerAmount: -50,
                        cardHolderAmount: -100,
                        kardFees: 0,
                        description: "Value adjusted upon request of issuer",
                        type: "ADJUSTMENT",
                        createdAt: "2024-10-02T00:00:00Z",
                    },
                ],
            },
        };
        server
            .mockEndpoint()
            .put("/v2/billing/rewards/abd6e578-d130-44e6-bf4b-8dddb31038b0")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billingService.updateReward("abd6e578-d130-44e6-bf4b-8dddb31038b0", {
            issuerAmount: 0,
            cardHolderAmount: 0,
            kardFees: -50,
            description: "Waive fees for transaction",
        });
        expect(response).toEqual({
            data: {
                rewardId: "abd6e578-d130-44e6-bf4b-8dddb31038b0",
                transactionIds: ["5e27318c9b346f00087fbb32"],
                issuerId: "6e21318c9b346f12387ffe73",
                merchantId: "6e21318c9b346f12387ffe73",
                offerId: "6e21318c9b346f12387ffe73",
                userId: "6e21318c9b346f12387ffe73",
                transactionAmount: 3000,
                transactionTimestamp: "2024-10-01T01:23:45.67Z",
                issuerAmount: 100,
                cardHolderAmount: 400,
                kardFees: 50,
                createdDate: "2024-10-01T00:00:00Z",
                lastModified: "2024-10-02T00:00:00Z",
                entries: [
                    {
                        issuerAmount: 150,
                        cardHolderAmount: 500,
                        kardFees: 50,
                        description: "Reward payout for transaction",
                        type: "MATCHED",
                        createdAt: "2024-10-01T00:00:00Z",
                    },
                    {
                        issuerAmount: -50,
                        cardHolderAmount: -100,
                        kardFees: 0,
                        description: "Value adjusted upon request of issuer",
                        type: "ADJUSTMENT",
                        createdAt: "2024-10-02T00:00:00Z",
                    },
                ],
            },
        });
    });

    test("updateReward (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { issuerAmount: 1, cardHolderAmount: 1, kardFees: 1, description: "description" };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .put("/v2/billing/rewards/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.updateReward("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32", {
                issuerAmount: 1,
                cardHolderAmount: 1,
                kardFees: 1,
                description: "description",
            });
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("updateReward (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { issuerAmount: 1, cardHolderAmount: 1, kardFees: 1, description: "description" };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .put("/v2/billing/rewards/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.updateReward("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32", {
                issuerAmount: 1,
                cardHolderAmount: 1,
                kardFees: 1,
                description: "description",
            });
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("updateReward (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { issuerAmount: 1, cardHolderAmount: 1, kardFees: 1, description: "description" };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .put("/v2/billing/rewards/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.updateReward("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32", {
                issuerAmount: 1,
                cardHolderAmount: 1,
                kardFees: 1,
                description: "description",
            });
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("updateReward (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { issuerAmount: 1, cardHolderAmount: 1, kardFees: 1, description: "description" };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .put("/v2/billing/rewards/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.updateReward("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32", {
                issuerAmount: 1,
                cardHolderAmount: 1,
                kardFees: 1,
                description: "description",
            });
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("revertReward (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { reverted: 5 } };
        server
            .mockEndpoint()
            .delete("/v2/billing/rewards/82ed6e40-f2f6-4f66-be17-52c03ad64414")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billingService.revertReward("82ed6e40-f2f6-4f66-be17-52c03ad64414");
        expect(response).toEqual({
            data: {
                reverted: 5,
            },
        });
    });

    test("revertReward (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/v2/billing/rewards/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.revertReward("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32");
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("revertReward (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/v2/billing/rewards/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.revertReward("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32");
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("revertReward (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/v2/billing/rewards/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.revertReward("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32");
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("revertRewards (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { reverted: 5 } };
        server
            .mockEndpoint()
            .delete("/v2/billing/rewards")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billingService.revertRewards();
        expect(response).toEqual({
            data: {
                reverted: 5,
            },
        });
    });

    test("revertRewards (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/v2/billing/rewards")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.revertRewards();
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("revertRewards (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/v2/billing/rewards")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.revertRewards();
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("revertRewards (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/v2/billing/rewards")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.revertRewards();
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("uploadInvoiceStatus (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { url: "url", expires: "expires" } };
        server
            .mockEndpoint()
            .get("/v2/billing/invoice/status/upload")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billingService.uploadInvoiceStatus();
        expect(response).toEqual({
            data: {
                url: "url",
                expires: "expires",
            },
        });
    });

    test("uploadInvoiceStatus (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/billing/invoice/status/upload")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.uploadInvoiceStatus();
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("uploadInvoiceStatus (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/billing/invoice/status/upload")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.uploadInvoiceStatus();
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("uploadInvoiceStatus (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/billing/invoice/status/upload")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.uploadInvoiceStatus();
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("triggerMerchantInvoice (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { startDate: "2024-01-15T09:30:00Z", endDate: "2024-01-15T09:30:00Z" };
        const rawResponseBody = { invoiceName: "invoiceName" };
        server
            .mockEndpoint()
            .post("/v2/billing/merchants/merchantId/invoices")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billingService.triggerMerchantInvoice("merchantId", {
            startDate: "2024-01-15T09:30:00Z",
            endDate: "2024-01-15T09:30:00Z",
        });
        expect(response).toEqual({
            invoiceName: "invoiceName",
        });
    });

    test("triggerMerchantInvoice (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { startDate: "2024-01-15T09:30:00Z", endDate: "2024-01-15T09:30:00Z" };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/billing/merchants/merchantId/invoices")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.triggerMerchantInvoice("merchantId", {
                startDate: "2024-01-15T09:30:00Z",
                endDate: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("triggerMerchantInvoice (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { startDate: "2024-01-15T09:30:00Z", endDate: "2024-01-15T09:30:00Z" };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/billing/merchants/merchantId/invoices")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.triggerMerchantInvoice("merchantId", {
                startDate: "2024-01-15T09:30:00Z",
                endDate: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("triggerMerchantInvoice (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { startDate: "2024-01-15T09:30:00Z", endDate: "2024-01-15T09:30:00Z" };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/billing/merchants/merchantId/invoices")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billingService.triggerMerchantInvoice("merchantId", {
                startDate: "2024-01-15T09:30:00Z",
                endDate: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });
});
