// This file was auto-generated by Fern from our API Definition.

import * as KardApi from "../../src/api/index";
import { KardApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("FilesClient", () => {
    test("internalSaveFile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    id: "id",
                    type: "earnedRewardApprovedDailyReconciliationFile",
                    attributes: {
                        fileName: "fileName",
                        bucketName: "bucketName",
                        lastModified: "lastModified",
                        sentAt: "sentAt",
                    },
                    relationships: { relationships: { data: { type: "type", id: "id" } } },
                },
                {
                    id: "id",
                    type: "earnedRewardApprovedDailyReconciliationFile",
                    attributes: {
                        fileName: "fileName",
                        bucketName: "bucketName",
                        lastModified: "lastModified",
                        sentAt: "sentAt",
                    },
                    relationships: { relationships: { data: { type: "type", id: "id" } } },
                },
            ],
        };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/internal/files/issuers/organizationId/metadata")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.internalSaveFile("organizationId", {
            data: [
                {
                    id: "id",
                    type: "earnedRewardApprovedDailyReconciliationFile",
                    attributes: {
                        fileName: "fileName",
                        bucketName: "bucketName",
                        lastModified: "lastModified",
                        sentAt: "sentAt",
                    },
                    relationships: {
                        relationships: {
                            data: {
                                type: "type",
                                id: "id",
                            },
                        },
                    },
                },
                {
                    id: "id",
                    type: "earnedRewardApprovedDailyReconciliationFile",
                    attributes: {
                        fileName: "fileName",
                        bucketName: "bucketName",
                        lastModified: "lastModified",
                        sentAt: "sentAt",
                    },
                    relationships: {
                        relationships: {
                            data: {
                                type: "type",
                                id: "id",
                            },
                        },
                    },
                },
            ],
        });
        expect(response).toEqual({
            message: "message",
        });
    });

    test("internalSaveFile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    id: "id",
                    type: "earnedRewardApprovedDailyReconciliationFile",
                    attributes: {
                        fileName: "fileName",
                        bucketName: "bucketName",
                        lastModified: "lastModified",
                        sentAt: "sentAt",
                    },
                    relationships: { relationships: { data: { type: "type", id: "id" } } },
                },
                {
                    id: "id",
                    type: "earnedRewardApprovedDailyReconciliationFile",
                    attributes: {
                        fileName: "fileName",
                        bucketName: "bucketName",
                        lastModified: "lastModified",
                        sentAt: "sentAt",
                    },
                    relationships: { relationships: { data: { type: "type", id: "id" } } },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/internal/files/issuers/organizationId/metadata")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.internalSaveFile("organizationId", {
                data: [
                    {
                        id: "id",
                        type: "earnedRewardApprovedDailyReconciliationFile",
                        attributes: {
                            fileName: "fileName",
                            bucketName: "bucketName",
                            lastModified: "lastModified",
                            sentAt: "sentAt",
                        },
                        relationships: {
                            relationships: {
                                data: {
                                    type: "type",
                                    id: "id",
                                },
                            },
                        },
                    },
                    {
                        id: "id",
                        type: "earnedRewardApprovedDailyReconciliationFile",
                        attributes: {
                            fileName: "fileName",
                            bucketName: "bucketName",
                            lastModified: "lastModified",
                            sentAt: "sentAt",
                        },
                        relationships: {
                            relationships: {
                                data: {
                                    type: "type",
                                    id: "id",
                                },
                            },
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("internalSaveFile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    id: "id",
                    type: "earnedRewardApprovedDailyReconciliationFile",
                    attributes: {
                        fileName: "fileName",
                        bucketName: "bucketName",
                        lastModified: "lastModified",
                        sentAt: "sentAt",
                    },
                    relationships: { relationships: { data: { type: "type", id: "id" } } },
                },
                {
                    id: "id",
                    type: "earnedRewardApprovedDailyReconciliationFile",
                    attributes: {
                        fileName: "fileName",
                        bucketName: "bucketName",
                        lastModified: "lastModified",
                        sentAt: "sentAt",
                    },
                    relationships: { relationships: { data: { type: "type", id: "id" } } },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/internal/files/issuers/organizationId/metadata")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.internalSaveFile("organizationId", {
                data: [
                    {
                        id: "id",
                        type: "earnedRewardApprovedDailyReconciliationFile",
                        attributes: {
                            fileName: "fileName",
                            bucketName: "bucketName",
                            lastModified: "lastModified",
                            sentAt: "sentAt",
                        },
                        relationships: {
                            relationships: {
                                data: {
                                    type: "type",
                                    id: "id",
                                },
                            },
                        },
                    },
                    {
                        id: "id",
                        type: "earnedRewardApprovedDailyReconciliationFile",
                        attributes: {
                            fileName: "fileName",
                            bucketName: "bucketName",
                            lastModified: "lastModified",
                            sentAt: "sentAt",
                        },
                        relationships: {
                            relationships: {
                                data: {
                                    type: "type",
                                    id: "id",
                                },
                            },
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("internalSaveFile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    id: "id",
                    type: "earnedRewardApprovedDailyReconciliationFile",
                    attributes: {
                        fileName: "fileName",
                        bucketName: "bucketName",
                        lastModified: "lastModified",
                        sentAt: "sentAt",
                    },
                    relationships: { relationships: { data: { type: "type", id: "id" } } },
                },
                {
                    id: "id",
                    type: "earnedRewardApprovedDailyReconciliationFile",
                    attributes: {
                        fileName: "fileName",
                        bucketName: "bucketName",
                        lastModified: "lastModified",
                        sentAt: "sentAt",
                    },
                    relationships: { relationships: { data: { type: "type", id: "id" } } },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/internal/files/issuers/organizationId/metadata")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.internalSaveFile("organizationId", {
                data: [
                    {
                        id: "id",
                        type: "earnedRewardApprovedDailyReconciliationFile",
                        attributes: {
                            fileName: "fileName",
                            bucketName: "bucketName",
                            lastModified: "lastModified",
                            sentAt: "sentAt",
                        },
                        relationships: {
                            relationships: {
                                data: {
                                    type: "type",
                                    id: "id",
                                },
                            },
                        },
                    },
                    {
                        id: "id",
                        type: "earnedRewardApprovedDailyReconciliationFile",
                        attributes: {
                            fileName: "fileName",
                            bucketName: "bucketName",
                            lastModified: "lastModified",
                            sentAt: "sentAt",
                        },
                        relationships: {
                            relationships: {
                                data: {
                                    type: "type",
                                    id: "id",
                                },
                            },
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("getMetadata (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    type: "earnedRewardApprovedDailyReconciliationFile",
                    attributes: {
                        fileName: "test-file-10.jsonl",
                        sentAt: "2025-03-09T21:56:23Z",
                        lastModified: "2025-03-19T21:56:23Z",
                        downloadUrl:
                            "https://default-bucket.s3.us-east-1.amazonaws.com/test-file-10.jsonl?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Checksum-Mode=ENABLED&X-Amz-Credential=test%2F20250320%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250320T172109Z&X-Amz-Expires=1800&X-Amz-SignedHeaders=host&x-id=GetObject&X-Amz-Signature=c2a7dc6d14d0465b9ba9c24d47574a6bbcfa57856529319f25424c6bb1cf5204",
                    },
                    id: "67db3d87cb70469be876c852049",
                },
            ],
            links: {
                self: "/v2/files/issuers/0004321/metadata?page%5Bafter%5D=MjAyNS0wMy0xMFQyMTo1NjoyMy40OTY4ODda&page%5Bsize%5D=5&sort%5Bsent_at%5D=DESC",
                prev: "/v2/files/issuers/0004321/metadata?page%5Bbefore%5D=MjAyNS0wMy0wOVQyMTo1NjoyMy40OTY4ODda&page%5Bsize%5D=5&sort%5Bsent_at%5D=DESC",
                next: "/v2/files/issuers/0004321/metadata?page%5Bafter%5D=MjAyNS0wMy0wNVQyMTo1NjoyMy40OTY4ODda&page%5Bsize%5D=5&sort%5Bsent_at%5D=DESC",
            },
            meta: { pageSize: 5, hasNextPage: true },
        };
        server
            .mockEndpoint()
            .get("/v2/issuers/organization-123/files/metadata")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.getMetadata("organization-123", {
            "page[size]": 5,
            "filter[dateFrom]": "2025-02-20T21:56:23Z",
            "filter[dateTo]": "2025-03-20T21:56:23Z",
            "filter[fileType]": "earnedRewardApprovedDailyReconciliationFile",
            sort: "-sentDate",
        });
        expect(response).toEqual({
            data: [
                {
                    type: "earnedRewardApprovedDailyReconciliationFile",
                    attributes: {
                        fileName: "test-file-10.jsonl",
                        sentAt: "2025-03-09T21:56:23Z",
                        lastModified: "2025-03-19T21:56:23Z",
                        downloadUrl:
                            "https://default-bucket.s3.us-east-1.amazonaws.com/test-file-10.jsonl?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Checksum-Mode=ENABLED&X-Amz-Credential=test%2F20250320%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250320T172109Z&X-Amz-Expires=1800&X-Amz-SignedHeaders=host&x-id=GetObject&X-Amz-Signature=c2a7dc6d14d0465b9ba9c24d47574a6bbcfa57856529319f25424c6bb1cf5204",
                    },
                    id: "67db3d87cb70469be876c852049",
                },
            ],
            links: {
                self: "/v2/files/issuers/0004321/metadata?page%5Bafter%5D=MjAyNS0wMy0xMFQyMTo1NjoyMy40OTY4ODda&page%5Bsize%5D=5&sort%5Bsent_at%5D=DESC",
                prev: "/v2/files/issuers/0004321/metadata?page%5Bbefore%5D=MjAyNS0wMy0wOVQyMTo1NjoyMy40OTY4ODda&page%5Bsize%5D=5&sort%5Bsent_at%5D=DESC",
                next: "/v2/files/issuers/0004321/metadata?page%5Bafter%5D=MjAyNS0wMy0wNVQyMTo1NjoyMy40OTY4ODda&page%5Bsize%5D=5&sort%5Bsent_at%5D=DESC",
            },
            meta: {
                pageSize: 5,
                hasNextPage: true,
            },
        });
    });

    test("getMetadata (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/files/metadata")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.getMetadata("organizationId");
        }).rejects.toThrow(KardApi.ForbiddenError);
    });

    test("getMetadata (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/files/metadata")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.getMetadata("organizationId");
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("getMetadata (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/files/metadata")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.getMetadata("organizationId");
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("getMetadata (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/files/metadata")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.getMetadata("organizationId");
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });
});
