// This file was auto-generated by Fern from our API Definition.

import * as KardApi from "../../src/api/index";
import { KardApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PingClient", () => {
    test("ping (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "Ping successful", status: "OK", timestamp: "02/Oct/2025:17:52:43 +0000" };
        server.mockEndpoint().get("/v2/ping").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.ping.ping();
        expect(response).toEqual({
            message: "Ping successful",
            status: "OK",
            timestamp: "02/Oct/2025:17:52:43 +0000",
        });
    });

    test("ping (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };
        server.mockEndpoint().get("/v2/ping").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ping.ping();
        }).rejects.toThrow(KardApi.NetworkBlockedError);
    });
});
