// This file was auto-generated by Fern from our API Definition.

import * as KardApi from "../../src/api/index";
import { KardApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TransactionsClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "transaction",
                    id: "309rjfoincor3icno3rind093cdow3jciwjdwcm",
                    attributes: {
                        userId: "6FHt5b6Fnp0qdomMEy5AN6PXcSJIeX69",
                        status: "APPROVED",
                        amount: 1000,
                        subtotal: 800,
                        currency: "USD",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        description: "ADVANCEAUTO",
                        description2: "ADVANCEAUTO",
                        mcc: "1234",
                        cardBIN: "123456",
                        cardLastFour: "4321",
                        authorizationDate: "2021-07-02T17:47:06Z",
                        merchant: {
                            id: "12345678901234567",
                            name: "ADVANCEAUTO",
                            addrStreet: "125 Main St",
                            addrCity: "Philadelphia",
                            addrState: "PA",
                            addrZipcode: "19147",
                            addrCountry: "United States",
                            latitude: "37.9419429",
                            longitude: "-73.1446869",
                            storeId: "12345",
                        },
                        authorizationCode: "123456",
                        retrievalReferenceNumber: "100804333919",
                        acquirerReferenceNumber: "1234567890123456789012345678",
                        systemTraceAuditNumber: "333828",
                        transactionId: "2467de37-cbdc-416d-a359-75de87bfffb0",
                        cardProductId: "1234567890123456789012345678",
                        processorMids: { processor: "VISA", mids: { vmid: "12345678901", vsid: "12345678" } },
                    },
                },
            ],
        };
        const rawResponseBody = {
            data: {
                type: "job",
                id: "c94a93a7-beb9-4e58-960c-2c812f849398",
                attributes: {
                    status: "queued",
                    message: "Incoming Transactions event successfully queued for processing",
                },
            },
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organization-123/transactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.create("organization-123", {
            data: [
                {
                    type: "transaction",
                    id: "309rjfoincor3icno3rind093cdow3jciwjdwcm",
                    attributes: {
                        userId: "6FHt5b6Fnp0qdomMEy5AN6PXcSJIeX69",
                        status: "APPROVED",
                        amount: 1000,
                        subtotal: 800,
                        currency: "USD",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        description: "ADVANCEAUTO",
                        description2: "ADVANCEAUTO",
                        mcc: "1234",
                        cardBIN: "123456",
                        cardLastFour: "4321",
                        authorizationDate: "2021-07-02T17:47:06Z",
                        merchant: {
                            id: "12345678901234567",
                            name: "ADVANCEAUTO",
                            addrStreet: "125 Main St",
                            addrCity: "Philadelphia",
                            addrState: "PA",
                            addrZipcode: "19147",
                            addrCountry: "United States",
                            latitude: "37.9419429",
                            longitude: "-73.1446869",
                            storeId: "12345",
                        },
                        authorizationCode: "123456",
                        retrievalReferenceNumber: "100804333919",
                        acquirerReferenceNumber: "1234567890123456789012345678",
                        systemTraceAuditNumber: "333828",
                        transactionId: "2467de37-cbdc-416d-a359-75de87bfffb0",
                        cardProductId: "1234567890123456789012345678",
                        processorMids: {
                            processor: "VISA",
                            mids: {
                                vmid: "12345678901",
                                vsid: "12345678",
                            },
                        },
                    },
                },
            ],
        });
        expect(response).toEqual({
            data: {
                type: "job",
                id: "c94a93a7-beb9-4e58-960c-2c812f849398",
                attributes: {
                    status: "queued",
                    message: "Incoming Transactions event successfully queued for processing",
                },
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "matchedTransaction",
                    id: "soduinfwoer82498h248h298heo2eic",
                    attributes: {
                        userId: "6FHt5b6Fnp0qdomMEy5AN6PXcSJIeX69",
                        amount: 1000,
                        subtotal: 800,
                        description: "ADVANCEAUTO",
                        authorizationDate: "2021-07-02T17:47:06Z",
                        paymentType: "CARD",
                        matchedOfferId: "5eb2d4a39ce24e00081488c4",
                        matchedLocationId: "5eb2d4a39ce24e00081488d5",
                        cardBIN: "12345",
                        direction: "DEBIT",
                        merchant: {
                            id: "12345678901234567",
                            name: "ADVANCEAUTO",
                            addrStreet: "125 Main St",
                            addrCity: "Philadephia",
                            addrState: "PA",
                            addrZipcode: "19147",
                            addrCountry: "United States",
                        },
                        cardLastFour: "4321",
                        authorizationCode: "1234",
                        retrievalReferenceNumber: "100804333919",
                        systemTraceAuditNumber: "333828",
                        acquirerReferenceNumber: "1234567890123456789012345678",
                        transactionId: "2467de37-cbdc-416d-a359-75de87bfffb0",
                        cardProductId: "1234567890123456789012345678",
                        orderId: "23q49807iklasdf238904",
                        receiptMedium: "ELECTRONIC",
                    },
                },
            ],
        };
        const rawResponseBody = {
            data: {
                type: "job",
                id: "c94a93a7-beb9-4e58-960c-2c812f849398",
                attributes: {
                    status: "queued",
                    message: "Incoming Transactions event successfully queued for processing",
                },
            },
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organization-123/transactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.create("organization-123", {
            data: [
                {
                    type: "matchedTransaction",
                    id: "soduinfwoer82498h248h298heo2eic",
                    attributes: {
                        userId: "6FHt5b6Fnp0qdomMEy5AN6PXcSJIeX69",
                        amount: 1000,
                        subtotal: 800,
                        description: "ADVANCEAUTO",
                        authorizationDate: "2021-07-02T17:47:06Z",
                        paymentType: "CARD",
                        matchedOfferId: "5eb2d4a39ce24e00081488c4",
                        matchedLocationId: "5eb2d4a39ce24e00081488d5",
                        cardBIN: "12345",
                        direction: "DEBIT",
                        merchant: {
                            id: "12345678901234567",
                            name: "ADVANCEAUTO",
                            addrStreet: "125 Main St",
                            addrCity: "Philadephia",
                            addrState: "PA",
                            addrZipcode: "19147",
                            addrCountry: "United States",
                        },
                        cardLastFour: "4321",
                        authorizationCode: "1234",
                        retrievalReferenceNumber: "100804333919",
                        systemTraceAuditNumber: "333828",
                        acquirerReferenceNumber: "1234567890123456789012345678",
                        transactionId: "2467de37-cbdc-416d-a359-75de87bfffb0",
                        cardProductId: "1234567890123456789012345678",
                        orderId: "23q49807iklasdf238904",
                        receiptMedium: "ELECTRONIC",
                    },
                },
            ],
        });
        expect(response).toEqual({
            data: {
                type: "job",
                id: "c94a93a7-beb9-4e58-960c-2c812f849398",
                attributes: {
                    status: "queued",
                    message: "Incoming Transactions event successfully queued for processing",
                },
            },
        });
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "matchedTransaction",
                    id: "unknown_payment_txn_12345",
                    attributes: {
                        userId: "6FHt5b6Fnp0qdomMEy5AN6PXcSJIeX69",
                        amount: 2500,
                        subtotal: 2000,
                        description: "ONLINE STORE PURCHASE",
                        authorizationDate: "2021-07-02T17:47:06Z",
                        paymentType: "UNKNOWN",
                        matchedOfferId: "5eb2d4a39ce24e00081488c4",
                        direction: "DEBIT",
                        merchant: {
                            id: "98765432109876543",
                            name: "ONLINE STORE",
                            addrStreet: "456 Web St",
                            addrCity: "Online City",
                            addrState: "CA",
                            addrZipcode: "90210",
                            addrCountry: "United States",
                        },
                        cardLastFour: "7890",
                        authorizationCode: "5678",
                        retrievalReferenceNumber: "200804333919",
                        systemTraceAuditNumber: "444939",
                        acquirerReferenceNumber: "9876543210987654321098765432",
                        transactionId: "unknown-txn-4567-efgh-ijkl-mnop-qrstuvwxyz01",
                        orderId: "online_order_789012",
                        receiptMedium: "ELECTRONIC",
                    },
                },
            ],
        };
        const rawResponseBody = {
            data: {
                type: "job",
                id: "c94a93a7-beb9-4e58-960c-2c812f849398",
                attributes: {
                    status: "queued",
                    message: "Incoming Transactions event successfully queued for processing",
                },
            },
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organization-123/transactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.create("organization-123", {
            data: [
                {
                    type: "matchedTransaction",
                    id: "unknown_payment_txn_12345",
                    attributes: {
                        userId: "6FHt5b6Fnp0qdomMEy5AN6PXcSJIeX69",
                        amount: 2500,
                        subtotal: 2000,
                        description: "ONLINE STORE PURCHASE",
                        authorizationDate: "2021-07-02T17:47:06Z",
                        paymentType: "UNKNOWN",
                        matchedOfferId: "5eb2d4a39ce24e00081488c4",
                        direction: "DEBIT",
                        merchant: {
                            id: "98765432109876543",
                            name: "ONLINE STORE",
                            addrStreet: "456 Web St",
                            addrCity: "Online City",
                            addrState: "CA",
                            addrZipcode: "90210",
                            addrCountry: "United States",
                        },
                        cardLastFour: "7890",
                        authorizationCode: "5678",
                        retrievalReferenceNumber: "200804333919",
                        systemTraceAuditNumber: "444939",
                        acquirerReferenceNumber: "9876543210987654321098765432",
                        transactionId: "unknown-txn-4567-efgh-ijkl-mnop-qrstuvwxyz01",
                        orderId: "online_order_789012",
                        receiptMedium: "ELECTRONIC",
                    },
                },
            ],
        });
        expect(response).toEqual({
            data: {
                type: "job",
                id: "c94a93a7-beb9-4e58-960c-2c812f849398",
                attributes: {
                    status: "queued",
                    message: "Incoming Transactions event successfully queued for processing",
                },
            },
        });
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "transaction",
                    id: "id",
                    attributes: {
                        userId: "userId",
                        amount: 1,
                        status: "APPROVED",
                        currency: "currency",
                        description: "description",
                        cardBIN: "cardBIN",
                        cardLastFour: "cardLastFour",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        transactionId: "transactionId",
                    },
                },
                {
                    type: "transaction",
                    id: "id",
                    attributes: {
                        userId: "userId",
                        amount: 1,
                        status: "APPROVED",
                        currency: "currency",
                        description: "description",
                        cardBIN: "cardBIN",
                        cardLastFour: "cardLastFour",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        transactionId: "transactionId",
                    },
                },
            ],
        };
        const rawResponseBody = {
            data: { type: "type", id: "id", attributes: { status: "queued", message: "message" } },
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/transactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(207)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.create("organizationId", {
            data: [
                {
                    type: "transaction",
                    id: "id",
                    attributes: {
                        userId: "userId",
                        amount: 1,
                        status: "APPROVED",
                        currency: "currency",
                        description: "description",
                        cardBIN: "cardBIN",
                        cardLastFour: "cardLastFour",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        transactionId: "transactionId",
                    },
                },
                {
                    type: "transaction",
                    id: "id",
                    attributes: {
                        userId: "userId",
                        amount: 1,
                        status: "APPROVED",
                        currency: "currency",
                        description: "description",
                        cardBIN: "cardBIN",
                        cardLastFour: "cardLastFour",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        transactionId: "transactionId",
                    },
                },
            ],
        });
        expect(response).toEqual(KardApi.CreateIncomingTransactionsMultiStatus);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "transaction",
                    id: "id",
                    attributes: {
                        userId: "userId",
                        amount: 1,
                        status: "APPROVED",
                        currency: "currency",
                        description: "description",
                        cardBIN: "cardBIN",
                        cardLastFour: "cardLastFour",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        transactionId: "transactionId",
                    },
                },
                {
                    type: "transaction",
                    id: "id",
                    attributes: {
                        userId: "userId",
                        amount: 1,
                        status: "APPROVED",
                        currency: "currency",
                        description: "description",
                        cardBIN: "cardBIN",
                        cardLastFour: "cardLastFour",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        transactionId: "transactionId",
                    },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/transactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.create("organizationId", {
                data: [
                    {
                        type: "transaction",
                        id: "id",
                        attributes: {
                            userId: "userId",
                            amount: 1,
                            status: "APPROVED",
                            currency: "currency",
                            description: "description",
                            cardBIN: "cardBIN",
                            cardLastFour: "cardLastFour",
                            direction: "DEBIT",
                            paymentType: "CARD",
                            transactionId: "transactionId",
                        },
                    },
                    {
                        type: "transaction",
                        id: "id",
                        attributes: {
                            userId: "userId",
                            amount: 1,
                            status: "APPROVED",
                            currency: "currency",
                            description: "description",
                            cardBIN: "cardBIN",
                            cardLastFour: "cardLastFour",
                            direction: "DEBIT",
                            paymentType: "CARD",
                            transactionId: "transactionId",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "transaction",
                    id: "id",
                    attributes: {
                        userId: "userId",
                        amount: 1,
                        status: "APPROVED",
                        currency: "currency",
                        description: "description",
                        cardBIN: "cardBIN",
                        cardLastFour: "cardLastFour",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        transactionId: "transactionId",
                    },
                },
                {
                    type: "transaction",
                    id: "id",
                    attributes: {
                        userId: "userId",
                        amount: 1,
                        status: "APPROVED",
                        currency: "currency",
                        description: "description",
                        cardBIN: "cardBIN",
                        cardLastFour: "cardLastFour",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        transactionId: "transactionId",
                    },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/transactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.create("organizationId", {
                data: [
                    {
                        type: "transaction",
                        id: "id",
                        attributes: {
                            userId: "userId",
                            amount: 1,
                            status: "APPROVED",
                            currency: "currency",
                            description: "description",
                            cardBIN: "cardBIN",
                            cardLastFour: "cardLastFour",
                            direction: "DEBIT",
                            paymentType: "CARD",
                            transactionId: "transactionId",
                        },
                    },
                    {
                        type: "transaction",
                        id: "id",
                        attributes: {
                            userId: "userId",
                            amount: 1,
                            status: "APPROVED",
                            currency: "currency",
                            description: "description",
                            cardBIN: "cardBIN",
                            cardLastFour: "cardLastFour",
                            direction: "DEBIT",
                            paymentType: "CARD",
                            transactionId: "transactionId",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "transaction",
                    id: "id",
                    attributes: {
                        userId: "userId",
                        amount: 1,
                        status: "APPROVED",
                        currency: "currency",
                        description: "description",
                        cardBIN: "cardBIN",
                        cardLastFour: "cardLastFour",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        transactionId: "transactionId",
                    },
                },
                {
                    type: "transaction",
                    id: "id",
                    attributes: {
                        userId: "userId",
                        amount: 1,
                        status: "APPROVED",
                        currency: "currency",
                        description: "description",
                        cardBIN: "cardBIN",
                        cardLastFour: "cardLastFour",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        transactionId: "transactionId",
                    },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/transactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.create("organizationId", {
                data: [
                    {
                        type: "transaction",
                        id: "id",
                        attributes: {
                            userId: "userId",
                            amount: 1,
                            status: "APPROVED",
                            currency: "currency",
                            description: "description",
                            cardBIN: "cardBIN",
                            cardLastFour: "cardLastFour",
                            direction: "DEBIT",
                            paymentType: "CARD",
                            transactionId: "transactionId",
                        },
                    },
                    {
                        type: "transaction",
                        id: "id",
                        attributes: {
                            userId: "userId",
                            amount: 1,
                            status: "APPROVED",
                            currency: "currency",
                            description: "description",
                            cardBIN: "cardBIN",
                            cardLastFour: "cardLastFour",
                            direction: "DEBIT",
                            paymentType: "CARD",
                            transactionId: "transactionId",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "transaction",
                    id: "id",
                    attributes: {
                        userId: "userId",
                        amount: 1,
                        status: "APPROVED",
                        currency: "currency",
                        description: "description",
                        cardBIN: "cardBIN",
                        cardLastFour: "cardLastFour",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        transactionId: "transactionId",
                    },
                },
                {
                    type: "transaction",
                    id: "id",
                    attributes: {
                        userId: "userId",
                        amount: 1,
                        status: "APPROVED",
                        currency: "currency",
                        description: "description",
                        cardBIN: "cardBIN",
                        cardLastFour: "cardLastFour",
                        direction: "DEBIT",
                        paymentType: "CARD",
                        transactionId: "transactionId",
                    },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/transactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.create("organizationId", {
                data: [
                    {
                        type: "transaction",
                        id: "id",
                        attributes: {
                            userId: "userId",
                            amount: 1,
                            status: "APPROVED",
                            currency: "currency",
                            description: "description",
                            cardBIN: "cardBIN",
                            cardLastFour: "cardLastFour",
                            direction: "DEBIT",
                            paymentType: "CARD",
                            transactionId: "transactionId",
                        },
                    },
                    {
                        type: "transaction",
                        id: "id",
                        attributes: {
                            userId: "userId",
                            amount: 1,
                            status: "APPROVED",
                            currency: "currency",
                            description: "description",
                            cardBIN: "cardBIN",
                            cardLastFour: "cardLastFour",
                            direction: "DEBIT",
                            paymentType: "CARD",
                            transactionId: "transactionId",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.ConflictError);
    });

    test("createFraudMarkers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [{ id: "myTxnId12345", type: "fraudulentTransaction", attributes: { userId: "userId123" } }],
        };
        const rawResponseBody = {
            data: [{ type: "fraudulentTransaction", id: "myTxnId123", attributes: { userId: "user123" } }],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organization-123/fraud")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.createFraudMarkers("organization-123", {
            data: [
                {
                    id: "myTxnId12345",
                    type: "fraudulentTransaction",
                    attributes: {
                        userId: "userId123",
                    },
                },
            ],
        });
        expect(response).toEqual({
            data: [
                {
                    type: "fraudulentTransaction",
                    id: "myTxnId123",
                    attributes: {
                        userId: "user123",
                    },
                },
            ],
        });
    });

    test("createFraudMarkers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                { id: "id", type: "type", attributes: { userId: "userId" } },
                { id: "id", type: "type", attributes: { userId: "userId" } },
            ],
        };
        const rawResponseBody = {
            data: [
                { id: "id", type: "type", attributes: { userId: "userId" } },
                { id: "id", type: "type", attributes: { userId: "userId" } },
            ],
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/fraud")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(207)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.createFraudMarkers("organizationId", {
            data: [
                {
                    id: "id",
                    type: "type",
                    attributes: {
                        userId: "userId",
                    },
                },
                {
                    id: "id",
                    type: "type",
                    attributes: {
                        userId: "userId",
                    },
                },
            ],
        });
        expect(response).toEqual(KardApi.FraudMultiStatus);
    });

    test("createFraudMarkers (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                { id: "id", type: "type", attributes: { userId: "userId" } },
                { id: "id", type: "type", attributes: { userId: "userId" } },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/fraud")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.createFraudMarkers("organizationId", {
                data: [
                    {
                        id: "id",
                        type: "type",
                        attributes: {
                            userId: "userId",
                        },
                    },
                    {
                        id: "id",
                        type: "type",
                        attributes: {
                            userId: "userId",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("createFraudMarkers (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                { id: "id", type: "type", attributes: { userId: "userId" } },
                { id: "id", type: "type", attributes: { userId: "userId" } },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/fraud")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.createFraudMarkers("organizationId", {
                data: [
                    {
                        id: "id",
                        type: "type",
                        attributes: {
                            userId: "userId",
                        },
                    },
                    {
                        id: "id",
                        type: "type",
                        attributes: {
                            userId: "userId",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("createFraudMarkers (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                { id: "id", type: "type", attributes: { userId: "userId" } },
                { id: "id", type: "type", attributes: { userId: "userId" } },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/fraud")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.createFraudMarkers("organizationId", {
                data: [
                    {
                        id: "id",
                        type: "type",
                        attributes: {
                            userId: "userId",
                        },
                    },
                    {
                        id: "id",
                        type: "type",
                        attributes: {
                            userId: "userId",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("createAudits (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "audit",
                    attributes: {
                        auditCode: 8001,
                        merchantName: "Caribbean Goodness",
                        auditDescription: "duplicate transaction",
                        transactionId: "issuerTransaction123",
                    },
                },
            ],
        };
        const rawResponseBody = {
            data: [
                {
                    type: "audit",
                    id: "d80a6f28-1b24-4d65-9e42-e1cf3379bc98",
                    attributes: { transactionId: "issuerTransaction123" },
                },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organization-123/users/user-123/audits")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.createAudits("organization-123", "user-123", {
            data: [
                {
                    type: "audit",
                    attributes: {
                        auditCode: 8001,
                        merchantName: "Caribbean Goodness",
                        auditDescription: "duplicate transaction",
                        transactionId: "issuerTransaction123",
                    },
                },
            ],
        });
        expect(response).toEqual({
            data: [
                {
                    type: "audit",
                    id: "d80a6f28-1b24-4d65-9e42-e1cf3379bc98",
                    attributes: {
                        transactionId: "issuerTransaction123",
                    },
                },
            ],
        });
    });

    test("createAudits (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/audits")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(207)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.createAudits("organizationId", "userId", {
            data: [
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
            ],
        });
        expect(response).toEqual(KardApi.CreateAuditMultiStatus);
    });

    test("createAudits (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/audits")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.createAudits("organizationId", "userId", {
                data: [
                    {
                        type: "audit",
                        attributes: {
                            auditCode: 1,
                            merchantName: "merchantName",
                            auditDescription: "auditDescription",
                            transactionId: "transactionId",
                        },
                    },
                    {
                        type: "audit",
                        attributes: {
                            auditCode: 1,
                            merchantName: "merchantName",
                            auditDescription: "auditDescription",
                            transactionId: "transactionId",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("createAudits (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/audits")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.createAudits("organizationId", "userId", {
                data: [
                    {
                        type: "audit",
                        attributes: {
                            auditCode: 1,
                            merchantName: "merchantName",
                            auditDescription: "auditDescription",
                            transactionId: "transactionId",
                        },
                    },
                    {
                        type: "audit",
                        attributes: {
                            auditCode: 1,
                            merchantName: "merchantName",
                            auditDescription: "auditDescription",
                            transactionId: "transactionId",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.InternalServerError);
    });

    test("createAudits (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/audits")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.createAudits("organizationId", "userId", {
                data: [
                    {
                        type: "audit",
                        attributes: {
                            auditCode: 1,
                            merchantName: "merchantName",
                            auditDescription: "auditDescription",
                            transactionId: "transactionId",
                        },
                    },
                    {
                        type: "audit",
                        attributes: {
                            auditCode: 1,
                            merchantName: "merchantName",
                            auditDescription: "auditDescription",
                            transactionId: "transactionId",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("createAudits (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/audits")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.createAudits("organizationId", "userId", {
                data: [
                    {
                        type: "audit",
                        attributes: {
                            auditCode: 1,
                            merchantName: "merchantName",
                            auditDescription: "auditDescription",
                            transactionId: "transactionId",
                        },
                    },
                    {
                        type: "audit",
                        attributes: {
                            auditCode: 1,
                            merchantName: "merchantName",
                            auditDescription: "auditDescription",
                            transactionId: "transactionId",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("createAudits (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
                {
                    type: "audit",
                    attributes: {
                        auditCode: 1,
                        merchantName: "merchantName",
                        auditDescription: "auditDescription",
                        transactionId: "transactionId",
                    },
                },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .post("/v2/issuers/organizationId/users/userId/audits")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.createAudits("organizationId", "userId", {
                data: [
                    {
                        type: "audit",
                        attributes: {
                            auditCode: 1,
                            merchantName: "merchantName",
                            auditDescription: "auditDescription",
                            transactionId: "transactionId",
                        },
                    },
                    {
                        type: "audit",
                        attributes: {
                            auditCode: 1,
                            merchantName: "merchantName",
                            auditDescription: "auditDescription",
                            transactionId: "transactionId",
                        },
                    },
                ],
            });
        }).rejects.toThrow(KardApi.ConflictError);
    });

    test("GetEarnedRewards (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    type: "rewardedTransaction",
                    id: "fcabf024-3870-41f3-9fbd-b43ea85a3d19",
                    attributes: {
                        status: "SETTLED",
                        transactionId: "TXN-20241001-F21-127964",
                        transactionAmountInCents: 12796,
                        transactionTimestamp: "2024-10-01T01:36:57Z",
                        paidToIssuer: "UNPAID",
                        payoutTimestamp: "2024-10-01T02:00:00Z",
                        cardBIN: "123456",
                        cardLastFour: "4321",
                        commissionEarned: {
                            issuer: { type: "cents", value: 102 },
                            user: { type: "cents", value: 320 },
                        },
                    },
                    relationships: {
                        user: { data: { type: "user", id: "8c52423a-c319-44ee-8fc7-508e97b43892" } },
                        merchant: { data: { type: "merchant", id: "633ed2ab30dcb60009dd5699" } },
                        offer: { data: { type: "offer", id: "OFF-F21-INSTORE-2024Q4-001" } },
                    },
                },
            ],
            links: {
                self: "/v2/issuers/org-123/users/user-456/earned-rewards?page[size]=10",
                next: "/v2/issuers/org-123/users/user-456/earned-rewards?page[size]=10&page[after]=eyJpZCI6ImZjYWJmMDI0LTM4NzAtNDFmMy05ZmJkLWI0M2VhODVhM2QxOSIsInRzIjoiMjAyNC0xMC0wMVQwMTozNjo1N1oifQ==",
            },
            included: [
                { type: "merchant", id: "633ed2ab30dcb60009dd5699", attributes: { name: "Forever 21" } },
                { type: "merchant", id: "5f3e2d1c40abc50008cc4821", attributes: { name: "Target" } },
                { type: "offer", id: "OFF-F21-INSTORE-2024Q4-001", attributes: { purchaseChannel: ["INSTORE"] } },
                { type: "offer", id: "OFF-TGT-ONLINE-2024Q4-002", attributes: { purchaseChannel: ["ONLINE"] } },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/issuers/org-123/users/user-456/earned-rewards")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.getEarnedRewards("org-123", "user-456", {
            "page[size]": 10,
        });
        expect(response).toEqual({
            data: [
                {
                    type: "rewardedTransaction",
                    id: "fcabf024-3870-41f3-9fbd-b43ea85a3d19",
                    attributes: {
                        status: "SETTLED",
                        transactionId: "TXN-20241001-F21-127964",
                        transactionAmountInCents: 12796,
                        transactionTimestamp: "2024-10-01T01:36:57Z",
                        paidToIssuer: "UNPAID",
                        payoutTimestamp: "2024-10-01T02:00:00Z",
                        cardBIN: "123456",
                        cardLastFour: "4321",
                        commissionEarned: {
                            issuer: {
                                type: "cents",
                                value: 102,
                            },
                            user: {
                                type: "cents",
                                value: 320,
                            },
                        },
                    },
                    relationships: {
                        user: {
                            data: {
                                type: "user",
                                id: "8c52423a-c319-44ee-8fc7-508e97b43892",
                            },
                        },
                        merchant: {
                            data: {
                                type: "merchant",
                                id: "633ed2ab30dcb60009dd5699",
                            },
                        },
                        offer: {
                            data: {
                                type: "offer",
                                id: "OFF-F21-INSTORE-2024Q4-001",
                            },
                        },
                    },
                },
            ],
            links: {
                self: "/v2/issuers/org-123/users/user-456/earned-rewards?page[size]=10",
                next: "/v2/issuers/org-123/users/user-456/earned-rewards?page[size]=10&page[after]=eyJpZCI6ImZjYWJmMDI0LTM4NzAtNDFmMy05ZmJkLWI0M2VhODVhM2QxOSIsInRzIjoiMjAyNC0xMC0wMVQwMTozNjo1N1oifQ==",
            },
            included: [
                {
                    type: "merchant",
                    id: "633ed2ab30dcb60009dd5699",
                    attributes: {
                        name: "Forever 21",
                    },
                },
                {
                    type: "merchant",
                    id: "5f3e2d1c40abc50008cc4821",
                    attributes: {
                        name: "Target",
                    },
                },
                {
                    type: "offer",
                    id: "OFF-F21-INSTORE-2024Q4-001",
                    attributes: {
                        purchaseChannel: ["INSTORE"],
                    },
                },
                {
                    type: "offer",
                    id: "OFF-TGT-ONLINE-2024Q4-002",
                    attributes: {
                        purchaseChannel: ["ONLINE"],
                    },
                },
            ],
        });
    });

    test("GetEarnedRewards (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/earned-rewards")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.getEarnedRewards("organizationId", "userId");
        }).rejects.toThrow(KardApi.InvalidRequest);
    });

    test("GetEarnedRewards (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/earned-rewards")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.getEarnedRewards("organizationId", "userId");
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("GetEarnedRewards (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/earned-rewards")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.getEarnedRewards("organizationId", "userId");
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("GetEarnedRewards (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/issuers/organizationId/users/userId/earned-rewards")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.getEarnedRewards("organizationId", "userId");
        }).rejects.toThrow(KardApi.InternalServerError);
    });
});
