// This file was auto-generated by Fern from our API Definition.

import * as KardApi from "../../src/api/index";
import { KardApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TxnMapServiceClient", () => {
    test("deleteTxnMap (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                { type: "matchedTransaction", id: "id" },
                { type: "matchedTransaction", id: "id" },
            ],
        };

        server
            .mockEndpoint()
            .put("/internal/txn-map/delete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.txnMapService.deleteTxnMap({
            data: [
                {
                    type: "matchedTransaction",
                    id: "id",
                },
                {
                    type: "matchedTransaction",
                    id: "id",
                },
            ],
        });
        expect(response).toEqual(undefined);
    });

    test("deleteTxnMap (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                { type: "matchedTransaction", id: "id" },
                { type: "matchedTransaction", id: "id" },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .put("/internal/txn-map/delete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.txnMapService.deleteTxnMap({
                data: [
                    {
                        type: "matchedTransaction",
                        id: "id",
                    },
                    {
                        type: "matchedTransaction",
                        id: "id",
                    },
                ],
            });
        }).rejects.toThrow(KardApi.UnauthorizedError);
    });

    test("deleteTxnMap (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                { type: "matchedTransaction", id: "id" },
                { type: "matchedTransaction", id: "id" },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .put("/internal/txn-map/delete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.txnMapService.deleteTxnMap({
                data: [
                    {
                        type: "matchedTransaction",
                        id: "id",
                    },
                    {
                        type: "matchedTransaction",
                        id: "id",
                    },
                ],
            });
        }).rejects.toThrow(KardApi.DoesNotExistError);
    });

    test("deleteTxnMap (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new KardApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                { type: "matchedTransaction", id: "id" },
                { type: "matchedTransaction", id: "id" },
            ],
        };
        const rawResponseBody = {
            errors: [
                { status: "status", title: "title", detail: "detail" },
                { status: "status", title: "title", detail: "detail" },
            ],
        };
        server
            .mockEndpoint()
            .put("/internal/txn-map/delete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.txnMapService.deleteTxnMap({
                data: [
                    {
                        type: "matchedTransaction",
                        id: "id",
                    },
                    {
                        type: "matchedTransaction",
                        id: "id",
                    },
                ],
            });
        }).rejects.toThrow(KardApi.InvalidRequest);
    });
});
