/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KardApi from "../../../index.js";

export interface OfferCommonFields {
    /** Terms and conditions on offer */
    terms: string;
    /** Maximum times cardholder can redeem offer, if applicable */
    maxRedemptions?: number;
    /** Name of offer */
    name: string;
    purchaseChannel: KardApi.PurchaseChannel[];
    userReward: KardApi.Commission;
    /** Assets associated with offer */
    assets: KardApi.Asset[];
    /** Beginning date of offer (UTC) */
    startDate: string;
    /** Expiration date of offer if applicable (UTC) */
    expirationDate: string;
    /** True returns only targeted offers, false returns only non-targeted offers */
    isTargeted: boolean;
    /** Minimum Transaction Amount required to redeem offer, if available on offer */
    minTransactionAmount?: KardApi.Amount;
    /** Maximum Transaction Amount allowed to redeem offer, if available on offer */
    maxTransactionAmount?: KardApi.Amount;
    /** Minimum Reward Amount, if available on offer */
    minRewardAmount?: KardApi.Amount;
    /** Maximum Reward Amount, if available on offer */
    maxRewardAmount?: KardApi.Amount;
    /** URL to the website of the offer provider */
    websiteUrl?: string;
    /** Description of the offer */
    description?: string;
}
