// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export interface Address {
    street: string;
    city: string;
    state: KardApi.State;
    zipCode: string;
}
