// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export interface AuditEventMetaProperties {
    author?: KardApi.AuditEventAuthor;
    message?: string;
    sourceUrl?: string;
    /** Additional properties that are not part of the schema */
    additionalProperties?: Record<string, unknown>;
}
