// This file was auto-generated by Fern from our API Definition.

/** Category of merchant. Please use URL Encode for non single word categories. (Food & Beverage should be Food%20%26%20Beverage) */
export const CategoryOption = {
    ArtsEntertainment: "Arts & Entertainment",
    BabyKidsToys: "Baby, Kids & Toys",
    BooksDigitalMedia: "Books & Digital Media",
    ClothingShoesAccessories: "Clothing, Shoes & Accessories",
    ComputersElectronicsSoftware: "Computers, Electronics & Software",
    Convenience: "Convenience",
    Gas: "Gas",
    DepartmentStores: "Department Stores",
    FoodBeverage: "Food & Beverage",
    HealthBeauty: "Health & Beauty",
    HomeGarden: "Home & Garden",
    Miscellaneous: "Miscellaneous",
    OccasionsGifts: "Occasions & Gifts",
    Pets: "Pets",
    SportsOutdoors: "Sports & Outdoors",
    SuppliesServices: "Supplies & Services",
    Travel: "Travel",
} as const;
export type CategoryOption = (typeof CategoryOption)[keyof typeof CategoryOption];
