/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KardApi from "../../../index.js";

export interface CommissionValue {
    /** The type of commission */
    type: KardApi.CommissionValueType;
    /** The commission value. */
    value: number;
}
