// This file was auto-generated by Fern from our API Definition.

export interface ErrorSource {
    /** A JSON pointer to the value in the request document that caused the error */
    pointer?: string;
    /** A string indicating which URI query parameter caused the error */
    parameter?: string;
    /** A string indicating the name of a single request header which caused the error */
    header?: string;
}
