/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NotificationType =
    | "earnedRewardApproved"
    | "earnedRewardSettled"
    | "validTransaction"
    | "failedTransaction"
    | "clawback"
    | "offer"
    | "merchant"
    | "location"
    | "userOffer"
    | "auditUpdate";
export const NotificationType = {
    EarnedRewardApproved: "earnedRewardApproved",
    EarnedRewardSettled: "earnedRewardSettled",
    ValidTransaction: "validTransaction",
    FailedTransaction: "failedTransaction",
    Clawback: "clawback",
    Offer: "offer",
    Merchant: "merchant",
    Location: "location",
    UserOffer: "userOffer",
    AuditUpdate: "auditUpdate",
} as const;
