// This file was auto-generated by Fern from our API Definition.

export interface OperatingHours {
    SUNDAY?: string;
    MONDAY?: string;
    TUESDAY?: string;
    WEDNESDAY?: string;
    THURSDAY?: string;
    FRIDAY?: string;
    SATURDAY?: string;
}
