// This file was auto-generated by Fern from our API Definition.

/**
 * Pagination query parameters
 */
export interface Page {
    /** Represents a cursor value, and if provided, returns the next page of results */
    "page[after]"?: string;
    /** Represents a cursor value, and if provided, returns the previous page of results */
    "page[before]"?: string;
    /** Maximum number of records to be returned [1 - 200], (default = 200) */
    "page[size]"?: number;
}
