// This file was auto-generated by Fern from our API Definition.

import { AuthClient } from "./api/resources/auth/client/Client.js";
import { FilesClient } from "./api/resources/files/client/Client.js";
import { NotificationsClient } from "./api/resources/notifications/client/Client.js";
import { PingClient } from "./api/resources/ping/client/Client.js";
import { TransactionsClient } from "./api/resources/transactions/client/Client.js";
import { UsersClient } from "./api/resources/users/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace KardApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class KardApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<KardApiClient.Options>;
    protected _auth: AuthClient | undefined;
    protected _files: FilesClient | undefined;
    protected _notifications: NotificationsClient | undefined;
    protected _ping: PingClient | undefined;
    protected _transactions: TransactionsClient | undefined;
    protected _users: UsersClient | undefined;

    constructor(options: KardApiClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get auth(): AuthClient {
        return (this._auth ??= new AuthClient(this._options));
    }

    public get files(): FilesClient {
        return (this._files ??= new FilesClient(this._options));
    }

    public get notifications(): NotificationsClient {
        return (this._notifications ??= new NotificationsClient(this._options));
    }

    public get ping(): PingClient {
        return (this._ping ??= new PingClient(this._options));
    }

    public get transactions(): TransactionsClient {
        return (this._transactions ??= new TransactionsClient(this._options));
    }

    public get users(): UsersClient {
        return (this._users ??= new UsersClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
