/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const KardApiEnvironment = {
    Production: "https://rewards-api.getkard.com",
    Sandbox: "https://test-rewards-api.getkard.com",
} as const;

export type KardApiEnvironment = typeof KardApiEnvironment.Production | typeof KardApiEnvironment.Sandbox;
