// This file was auto-generated by Fern from our API Definition.

export const BrokerAssetType = {
    LogoImage: "LOGO_IMAGE",
    BannerImage: "BANNER_IMAGE",
} as const;
export type BrokerAssetType = (typeof BrokerAssetType)[keyof typeof BrokerAssetType];
