/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BrokerRewardType = "PERCENT" | "FLAT";
export const BrokerRewardType = {
    Percent: "PERCENT",
    Flat: "FLAT",
} as const;
