/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KardApi from "../../../index.js";

export interface CreatedSubscription extends KardApi.SubscriptionRequest {
    /** The ID of the subscription */
    id: string;
}
