/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KardApi from "../../../index.js";

export interface EarnedRewardSettledAttributes extends KardApi.RewardNotificationAttributes {
    commissionEarned: KardApi.CommissionValue;
}
