// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export interface EmailNotificationPlacementFileRelationships {
    placement: KardApi.RelationshipSingle;
    contentStrategy?: KardApi.RelationshipSingle | undefined;
}
