// This file was auto-generated by Fern from our API Definition.

export interface EmailNotificationPlacementFileAttributes {
    /** The display name of the placement */
    name: string;
    /** The issuer organization ID the placement belongs to */
    organizationId: string;
    /** The number of offer slots available in the placement */
    availableSlots: number;
    /** The delivery cadence of the placement (e.g. MONTHLY) */
    cadence: string;
    /** Presigned URL to download the generated placement file (gzipped JSONL) */
    downloadUrl: string;
}
