// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export interface FailedTransactionData {
    /** The internal ID of the notification */
    id: string;
    attributes: KardApi.FailedTransactionAttributes;
    relationships: KardApi.FailedTransactionRelationships;
}
