/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LocationStatus = "ACTIVE" | "INACTIVE";
export const LocationStatus = {
    Active: "ACTIVE",
    Inactive: "INACTIVE",
} as const;
