/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NotificationType =
    | "earnedRewardApproved"
    | "earnedRewardSettled"
    | "validTransaction"
    | "failedTransaction"
    | "clawback"
    | "offerCreated"
    | "merchantCreated"
    | "locationCreated"
    | "userOfferCreated"
    | "auditUpdate";
export const NotificationType = {
    EarnedRewardApproved: "earnedRewardApproved",
    EarnedRewardSettled: "earnedRewardSettled",
    ValidTransaction: "validTransaction",
    FailedTransaction: "failedTransaction",
    Clawback: "clawback",
    OfferCreated: "offerCreated",
    MerchantCreated: "merchantCreated",
    LocationCreated: "locationCreated",
    UserOfferCreated: "userOfferCreated",
    AuditUpdate: "auditUpdate",
} as const;
