// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export type NotificationDataUnion =
    | KardApi.NotificationDataUnion.EarnedRewardApproved
    | KardApi.NotificationDataUnion.EarnedRewardSettled
    | KardApi.NotificationDataUnion.ValidTransaction
    | KardApi.NotificationDataUnion.FailedTransaction
    | KardApi.NotificationDataUnion.Clawback
    | KardApi.NotificationDataUnion.AuditUpdate
    | KardApi.NotificationDataUnion.FileProcessingResult;

export namespace NotificationDataUnion {
    export interface EarnedRewardApproved extends KardApi.EarnedRewardApprovedData {
        type: "earnedRewardApproved";
    }

    export interface EarnedRewardSettled extends KardApi.EarnedRewardSettledData {
        type: "earnedRewardSettled";
    }

    export interface ValidTransaction extends KardApi.ValidTransactionData {
        type: "validTransaction";
    }

    export interface FailedTransaction extends KardApi.FailedTransactionData {
        type: "failedTransaction";
    }

    export interface Clawback extends KardApi.ClawbackData {
        type: "clawback";
    }

    export interface AuditUpdate extends KardApi.AuditUpdateData {
        type: "auditUpdate";
    }

    export interface FileProcessingResult extends KardApi.FileResultData {
        type: "fileProcessingResult";
    }
}
