// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * @example
 *     {
 *         data: {
 *             type: "earnedRewardSettled",
 *             id: "d80a6f28-1b24-4d65-9e42-e1cf3379bc98",
 *             attributes: {
 *                 message: "You have earned a 72 cent reward on your transaction at McDonald's",
 *                 name: "McDonald's",
 *                 commissionEarned: {
 *                     type: KardApi.CommissionValueType.Cents,
 *                     value: 72
 *                 },
 *                 attributionUrl: "www.attribution.com/token",
 *                 surveyUrl: "www.survey.com",
 *                 cardProductId: "card_product_123"
 *             },
 *             relationships: {
 *                 user: {
 *                     data: {
 *                         type: "user",
 *                         id: "1234567890"
 *                     }
 *                 },
 *                 transaction: {
 *                     data: {
 *                         type: "transaction",
 *                         id: "0987654321"
 *                     }
 *                 }
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         data: {
 *             type: "earnedRewardApproved",
 *             id: "d80a6f28-1b24-4d65-9e42-e1cf3379bc98",
 *             attributes: {
 *                 message: "You have earned a 72 cent reward on your transaction at McDonald's",
 *                 name: "McDonald's",
 *                 attributionUrl: "www.attribution.com/token",
 *                 surveyUrl: "www.survey.com",
 *                 cardProductId: "card_product_123"
 *             },
 *             relationships: {
 *                 user: {
 *                     data: {
 *                         type: "user",
 *                         id: "1234567890"
 *                     }
 *                 },
 *                 transaction: {
 *                     data: {
 *                         type: "transaction",
 *                         id: "0987654321"
 *                     }
 *                 }
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         data: {
 *             type: "validTransaction",
 *             id: "a12b34c56d78e90f1234",
 *             attributes: {
 *                 message: "Your transaction at Amazon has been validated successfully.",
 *                 name: "Amazon",
 *                 commissionEarned: {
 *                     issuer: {
 *                         type: KardApi.CommissionValueType.Cents,
 *                         value: 100
 *                     },
 *                     user: {
 *                         type: KardApi.CommissionValueType.Cents,
 *                         value: 320
 *                     }
 *                 },
 *                 attributionUrl: "www.attribution.com/token",
 *                 surveyUrl: "www.survey.com",
 *                 cardProductId: "card_product_123"
 *             },
 *             relationships: {
 *                 user: {
 *                     data: {
 *                         type: "user",
 *                         id: "9876543210"
 *                     }
 *                 },
 *                 offer: {
 *                     data: {
 *                         type: "offer",
 *                         id: "1234567890"
 *                     }
 *                 },
 *                 transaction: {
 *                     data: {
 *                         type: "transaction",
 *                         id: "0987654321"
 *                     }
 *                 }
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         data: {
 *             type: "failedTransaction",
 *             id: "a12b34c56d78e90f1234",
 *             attributes: {
 *                 message: "Transaction validation failed",
 *                 reason: "User is not part of the targeted audience eligible to redeem this offer",
 *                 name: "Walmart",
 *                 cardProductId: "card_product_123"
 *             },
 *             relationships: {
 *                 user: {
 *                     data: {
 *                         type: "user",
 *                         id: "9876543210"
 *                     }
 *                 },
 *                 offer: {
 *                     data: {
 *                         type: "offer",
 *                         id: "1234567890"
 *                     }
 *                 },
 *                 transaction: {
 *                     data: {
 *                         type: "transaction",
 *                         id: "0987654321"
 *                     }
 *                 }
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         data: {
 *             type: "clawback",
 *             id: "a12b34c56d78e90f1234",
 *             attributes: {
 *                 message: "Transaction has been marked for clawback",
 *                 reason: "This transaction was previously rewarded in another system",
 *                 name: "Starbucks",
 *                 cardProductId: "card_product_123"
 *             },
 *             relationships: {
 *                 user: {
 *                     data: {
 *                         type: "user",
 *                         id: "9876543210"
 *                     }
 *                 },
 *                 offer: {
 *                     data: {
 *                         type: "offer",
 *                         id: "1234567890"
 *                     }
 *                 },
 *                 transaction: {
 *                     data: {
 *                         type: "transaction",
 *                         id: "0987654321"
 *                     }
 *                 }
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         data: {
 *             type: "userOffer",
 *             id: "some-user-offer-notification-id",
 *             attributes: {
 *                 status: KardApi.UserOfferStatus.Active,
 *                 createdAt: "2025-06-23T00:00:00Z",
 *                 updatedAt: "2025-06-23T00:00:00Z",
 *                 eventPriority: 1
 *             },
 *             relationships: {
 *                 offer: {
 *                     data: {
 *                         type: "offer",
 *                         id: "restaurant-offer-id"
 *                     }
 *                 },
 *                 user: {
 *                     data: {
 *                         type: "user",
 *                         id: "user-123"
 *                     }
 *                 }
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         data: {
 *             type: "location",
 *             id: "some-location-notification-id",
 *             attributes: {
 *                 locationId: "restaurant-location-id",
 *                 name: "Local Restaurant",
 *                 status: KardApi.LocationStatus.Active,
 *                 address: {
 *                     street: "120 Main St",
 *                     city: "Philadelphia",
 *                     state: "PA",
 *                     zipCode: "19147"
 *                 },
 *                 coordinates: {
 *                     longitude: -75.1446869,
 *                     latitude: 39.9419429
 *                 },
 *                 phone: "+1 (123) 555-8880",
 *                 operationHours: {
 *                     periods: [{
 *                             close: {
 *                                 day: 1,
 *                                 time: "1700"
 *                             },
 *                             open: {
 *                                 day: 1,
 *                                 time: "0900"
 *                             }
 *                         }, {
 *                             close: {
 *                                 day: 2,
 *                                 time: "1700"
 *                             },
 *                             open: {
 *                                 day: 2,
 *                                 time: "0900"
 *                             }
 *                         }, {
 *                             close: {
 *                                 day: 3,
 *                                 time: "1700"
 *                             },
 *                             open: {
 *                                 day: 3,
 *                                 time: "0900"
 *                             }
 *                         }, {
 *                             close: {
 *                                 day: 4,
 *                                 time: "1700"
 *                             },
 *                             open: {
 *                                 day: 4,
 *                                 time: "0900"
 *                             }
 *                         }, {
 *                             close: {
 *                                 day: 5,
 *                                 time: "1700"
 *                             },
 *                             open: {
 *                                 day: 5,
 *                                 time: "0900"
 *                             }
 *                         }],
 *                     weekdayText: ["Monday: 9:00 AM \u2013 5:00 PM", "Tuesday: 9:00 AM \u2013 5:00 PM", "Wednesday: 9:00 AM \u2013 5:00 PM", "Thursday: 9:00 AM \u2013 5:00 PM", "Friday: 9:00 AM \u2013 5:00 PM", "Saturday: Closed", "Sunday: Closed"]
 *                 },
 *                 createdAt: "2025-06-22T00:00:00Z",
 *                 updatedAt: "2025-06-22T00:00:00Z"
 *             },
 *             relationships: {
 *                 merchant: {
 *                     data: {
 *                         type: "merchant",
 *                         id: "restaurant-merchant-id"
 *                     }
 *                 }
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         data: {
 *             type: "offer",
 *             id: "some-offer-notification-id",
 *             attributes: {
 *                 offerId: "restaurant-offer-id",
 *                 offerType: KardApi.OfferType.StandardOffer,
 *                 name: "Local Restaurant",
 *                 terms: "This offer is valid for in-store purchases at participating locations and applies only to menu items as specified in the promotion details. Discounts cannot be combined with other promotions, applied to previous purchases, or redeemed for cash. The merchant reserves the right to modify or cancel the offer at any time without prior notice.",
 *                 status: KardApi.OfferStatus.Active,
 *                 purchaseChannel: [KardApi.BrokerPurchaseChannel.Instore, KardApi.BrokerPurchaseChannel.Online],
 *                 userReward: {
 *                     type: KardApi.BrokerRewardType.Percent,
 *                     value: 5
 *                 },
 *                 startDate: "2025-06-23T00:00:00Z",
 *                 expirationDate: "2025-07-10T00:00:00Z",
 *                 minRewardAmount: {
 *                     type: KardApi.BrokerAmountType.Cents,
 *                     value: 0
 *                 },
 *                 maxRewardAmount: {
 *                     type: KardApi.BrokerAmountType.Cents,
 *                     value: 2000
 *                 },
 *                 minUserRewardAmount: {
 *                     type: KardApi.BrokerAmountType.Cents,
 *                     value: 0
 *                 },
 *                 maxUserRewardAmount: {
 *                     type: KardApi.BrokerAmountType.Cents,
 *                     value: 2000
 *                 },
 *                 minTransactionAmount: {
 *                     type: KardApi.BrokerAmountType.Cents,
 *                     value: 500
 *                 },
 *                 maxTransactionAmount: {
 *                     type: KardApi.BrokerAmountType.Cents,
 *                     value: 10000
 *                 },
 *                 validMCCs: ["5812", "5813"],
 *                 maxRedemptions: 1,
 *                 isTargeted: false,
 *                 updatedAt: "2025-06-22T00:00:00Z",
 *                 createdAt: "2025-06-22T00:00:00Z"
 *             },
 *             relationships: {
 *                 merchant: {
 *                     data: {
 *                         type: "merchant",
 *                         id: "restaurant-merchant-id"
 *                     }
 *                 }
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         data: {
 *             type: "merchant",
 *             id: "some-merchant-notification-id",
 *             attributes: {
 *                 merchantId: "restaurant-merchant-id",
 *                 name: "Local Restaurant",
 *                 assets: [{
 *                         type: KardApi.BrokerAssetType.LogoImage,
 *                         url: "http://assets.getkard.com/logo/img",
 *                         alt: "Restaurant Logo Image"
 *                     }],
 *                 websiteUrl: "https://www.example-restaurant.com",
 *                 description: "A local restaurant offering delicious food and great dining experiences.",
 *                 source: KardApi.MerchantSource.National,
 *                 category: "Food & Beverage",
 *                 updatedAt: "2025-06-22T00:00:00Z",
 *                 createdAt: "2025-06-22T00:00:00Z"
 *             },
 *             relationships: {
 *                 offer: {
 *                     data: [{
 *                             type: "offer",
 *                             id: "restaurant-offer-id"
 *                         }]
 *                 }
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         data: {
 *             type: "auditUpdate",
 *             id: "a12b34c56d78e90f1234",
 *             attributes: {
 *                 status: KardApi.AuditStatus.InProgress,
 *                 auditCode: 8001,
 *                 merchantName: "Caribbean Goodness",
 *                 auditDescription: "duplicate",
 *                 transactionId: "txn-123"
 *             },
 *             relationships: {
 *                 user: {
 *                     data: {
 *                         type: "user",
 *                         id: "9876543210"
 *                     }
 *                 },
 *                 audit: {
 *                     data: {
 *                         type: "audit",
 *                         id: "5eb2d4a39ce24e00081488c4"
 *                     }
 *                 }
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         data: {
 *             type: "auditUpdate",
 *             id: "a12b34c56d78e90f1234",
 *             attributes: {
 *                 status: KardApi.AuditStatus.Closed,
 *                 auditCode: 3006,
 *                 merchantName: "Caribbean Goodness",
 *                 auditDescription: "reward was not given for offer",
 *                 transactionId: "txn-123",
 *                 resolutionDescription: "offer had expired",
 *                 resolutionTimeStamp: "2022-09-15T19:03:26.236Z",
 *                 resolutionCode: 9003
 *             },
 *             relationships: {
 *                 user: {
 *                     data: {
 *                         type: "user",
 *                         id: "9876543210"
 *                     }
 *                 },
 *                 audit: {
 *                     data: {
 *                         type: "audit",
 *                         id: "5eb2d4a39ce24e00081488c4"
 *                     }
 *                 }
 *             }
 *         }
 *     }
 */
export interface NotificationPayload {
    data: KardApi.NotificationDataUnion;
    meta?: KardApi.NotificationMetadata;
}
