// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export type NotificationUnion = KardApi.NotificationUnion.Notification;

export namespace NotificationUnion {
    export interface Notification extends KardApi.Notification {
        type: "notification";
    }
}
