/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OfferStatus = "INACTIVE" | "ACTIVE";
export const OfferStatus = {
    Inactive: "INACTIVE",
    Active: "ACTIVE",
} as const;
