// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

export interface PushNotificationPlacementFileData {
    /** The placement ID, also used as the notification resource ID */
    id: string;
    attributes: KardApi.PushNotificationPlacementFileAttributes;
    relationships: KardApi.PushNotificationPlacementFileRelationships;
}
