// This file was auto-generated by Fern from our API Definition.

export interface RewardNotificationAttributes {
    /** The display message associated to the notification */
    message: string;
    /** The name of the merchant */
    name: string;
    /** The attribution URL to track user's interactions with the notification */
    attributionUrl: string;
    /** Post experience survey URL, if available. This will be present for rewards associated with local offers. */
    surveyUrl?: string;
    /** The ID of the card product */
    cardProductId?: string;
}
