// This file was auto-generated by Fern from our API Definition.

export const UserOfferStatus = {
    Active: "ACTIVE",
    Inactive: "INACTIVE",
} as const;
export type UserOfferStatus = (typeof UserOfferStatus)[keyof typeof UserOfferStatus];
