/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UserOfferStatus = "ACTIVE" | "INACTIVE";
export const UserOfferStatus = {
    Active: "ACTIVE",
    Inactive: "INACTIVE",
} as const;
