/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KardApi from "../../../index.js";

export interface WebhookUserOfferRelationships {
    user: KardApi.RelationshipSingle;
    offer: KardApi.RelationshipSingle;
}
