/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KardApi from "../../../index.js";

export interface WebhookMerchantData {
    /** The internal ID of the notification */
    id: string;
    attributes: KardApi.WebhookMerchantAttributes;
    relationships: KardApi.WebhookMerchantRelationships;
}
