/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KardApi from "../../../index.js";

export interface WebhookOfferData {
    /** The internal ID of the notification */
    id: string;
    attributes: KardApi.WebhookOfferAttributes;
    relationships: KardApi.WebhookOfferRelationships;
}
