// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import type * as KardApi from "../../../index.js";

export class NetworkBlockedError extends errors.KardApiError {
    constructor(body: KardApi.NetworkBlockedErrorBody, rawResponse?: core.RawResponse) {
        super({
            message: "NetworkBlockedError",
            statusCode: 403,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, NetworkBlockedError.prototype);
    }
}
