// This file was auto-generated by Fern from our API Definition.

export interface User {
    _id: string;
    referringPartner: string;
    referringPartnerUserId: string;
    cards?: unknown[];
    email?: string;
    userName?: string;
    firstName?: string;
    lastName?: string;
    zipCode?: string;
    redeemedRewards?: unknown[];
    createdDate?: string;
    lastModified?: string;
    enrolledRewards?: string[];
    audiences?: string[];
    status?: string;
    experimentStatus?: unknown[];
    externalPartnerUserId?: string;
    lastUsed?: unknown;
}
