// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetSubscriptionsRequest {
    "filter[eventName]"?: KardApi.NotificationType;
}
