// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * Attribution details for offers.
 * This property is always required in the schema, but defaults will be applied by the server when not provided.
 * When isRequired=true, events must contain at least one item.
 *
 * @example
 *     {
 *         isRequired: true,
 *         events: [KardApi.AttributionEventType.Impression]
 *     }
 *
 * @example
 *     {
 *         isRequired: false,
 *         events: []
 *     }
 */
export interface Attribution {
    /** Whether attribution is required for this offer */
    isRequired: boolean;
    /**
     * List of attribution events.
     * When isRequired is true, this list must not be empty.
     * When omitted, an empty list will be provided by default.
     */
    events: KardApi.AttributionEventType[];
}
