// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * Included related resource (polymorphic)
 */
export type IncludedResource =
    | KardApi.MerchantResource
    | KardApi.LocationResource
    | KardApi.AudienceResource
    | KardApi.SegmentResource;
