// This file was auto-generated by Fern from our API Definition.

/**
 * Location resource
 */
export interface LocationResource {
    id: string;
    /** Resource type */
    type: "location";
    /** Location attributes */
    attributes: Record<string, unknown>;
}
