// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * Base attributes of an offer
 */
export interface OfferAttributes {
    /** Name of the offer */
    name: string;
    offerType?: KardApi.LocationType;
    /** Merchant Id in Kard's system */
    merchantId: string;
    /** Whether offer is specific to certain locations */
    isLocationSpecific?: boolean;
    /** Current status of the offer */
    status: KardApi.Status;
    /** Network the merchant belongs to */
    merchantNetwork: string;
    /** List of merchant location IDs where offer is valid */
    merchantLocationIds?: string[];
    /** Whether user opt-in is required */
    optInRequired?: boolean;
    /** List of qualified issuer IDs */
    qualifiedIssuer: string[];
    commissionType: KardApi.CommissionType;
    /** Commission value */
    commissionValue: number;
    /** Commission mapping by issuer */
    issuerCommissionsMap: Record<string, number>;
    /** User commission mapping */
    userCommissionsMap?: Record<string, number>;
    /** Whether this is a custom offer */
    isCustom?: boolean;
    /** Terms and conditions for the offer */
    terms?: string;
    /** Minimum transaction amount required */
    minTransactionAmount?: number;
    /** Maximum transaction amount allowed */
    maxTransactionAmount?: number;
    /** Minimum reward amount */
    minRewardAmount?: number;
    /** Maximum reward amount */
    maxRewardAmount?: number;
    /** Minimum user reward amount */
    minUserRewardAmount?: number;
    /** Maximum user reward amount */
    maxUserRewardAmount?: number;
    /** When the offer becomes active (ISO 8601 UTC) */
    startDate: string;
    /** When the offer expires (ISO 8601 UTC) */
    expirationDate: string;
    /** Whether offer can only be redeemed once per user */
    redeemableOnce?: boolean;
    source: KardApi.Source;
    /** Validation mapping by issuer */
    validOfferForIssuer?: Record<string, boolean>;
    /** Category of the offer */
    category?: string;
    /** Merchant category codes */
    mcc?: string[];
    /** Whether to always display this offer */
    displayAlways?: boolean;
    /** User audiences this offer targets */
    audiences?: string[];
    /** User segments this offer targets */
    segments?: string[];
    /** Partner's offer identifier */
    partnerOfferId?: string;
    /** If the offer is targeted or not (either has segments or audiences) */
    isTargeted: boolean;
    /** Attribution details for the offer */
    attribution: KardApi.Attribution;
    /** When the offer was created (ISO 8601 UTC) */
    createdDate?: string;
    /** When the offer was last modified (ISO 8601 UTC) */
    lastModified?: string;
}
