// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * Multi resource response containing offers with pagination
 */
export interface OffersListResponse {
    /** Array of offer resources */
    data: KardApi.OfferFormatUnion[];
    links?: KardApi.Links;
    /** Metadata about the pagination status */
    meta?: KardApi.PaginationMetadata;
    /** Included related resources (top-level for shared references) */
    included?: KardApi.IncludedResource[];
}
