// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../index.js";

/**
 * Relationships to other resources
 */
export interface OfferRelationships {
    merchant?: KardApi.RelationshipSingle;
    merchantLocations?: KardApi.RelationshipMultiple;
    audiences?: KardApi.RelationshipMultiple;
    segments?: KardApi.RelationshipMultiple;
}
