// This file was auto-generated by Fern from our API Definition.

/** Status of the offer */
export const Status = {
    Inactive: "INACTIVE",
    Active: "ACTIVE",
    Closed: "CLOSED",
} as const;
export type Status = (typeof Status)[keyof typeof Status];
