// This file was auto-generated by Fern from our API Definition.

import type * as KardApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface InternalGetAttributionsRequest {
    /** Filter by attribution type (offerAttribution or notificationAttribution) */
    "filter[type]"?: KardApi.InternalAttributionType;
    /** Filter by entity ID */
    "filter[entityId]"?: string;
    /** Filter by event code (IMPRESSION or VIEW) */
    "filter[eventCode]"?: KardApi.InternalEventCode;
    /** Filter attributions after this date (ISO 8601 format) */
    "filter[startDate]"?: string;
    /** Filter attributions before this date (ISO 8601 format) */
    "filter[endDate]"?: string;
    /** Cursor for forward pagination (next page). */
    "page[after]"?: string;
    /** Cursor for backward pagination (previous page). */
    "page[before]"?: string;
    /** Number of items per page. Defaults to 10 if not specified and maximum value allowed 100 items per page. */
    "page[size]"?: number;
}
